/**
 * EdKairos - Georgia 2021 <-> Common Core (CCSSM) crosswalk.
 * GENERATED FILE - do not hand-edit.
 *
 * GEORGIA IS PRIMARY. A CCSS code here is a REFERENCE label for a GA standard,
 * never the generation target. The two frameworks are not isomorphic: Georgia
 * moved content across grades, merged some CCSS clusters and split others, so a
 * row's `ccss` may sit at a different grade than its `ga`. That is correct, not
 * a bug.
 *
 * `source`:
 *   'existing-app-map' - carried over from the app's own skill->standards map
 *   'proposed'         - machine-proposed from the verbatim GA text, NOT yet
 *                        signed off by a Georgia mathematics educator
 * `reviewed` is false on every row until a human has approved it. Any surface
 * that SHOWS a CCSS code to a parent, teacher or district should check it.
 */

export type CrosswalkSource = 'existing-app-map' | 'proposed';
export type CrosswalkConfidence = 'carried' | 'high' | 'medium' | 'low';

export interface CrosswalkRow {
  ga: string;                 // GA 2021 learning-objective code
  ccss: string | null;        // best CCSSM analogue, or null when there is none
  alt: string[];              // other CCSS codes the app has associated with this GA code
  source: CrosswalkSource;
  confidence: CrosswalkConfidence;
  note: string | null;        // set when the mapping is not one-to-one
  reviewed: boolean;          // human sign-off
}

export const GA_CCSS_CROSSWALK: CrosswalkRow[] = [
  { ga: "K.GSR.8.1", ccss: "K.G.B.4", alt: [], source: "proposed", confidence: "high", note: "GA folds shape identification/sorting (K.G.A.2) into the analyze-and-compare expectation of K.G.B.4.", reviewed: false },
  { ga: "K.GSR.8.2", ccss: "K.G.A.1", alt: [], source: "proposed", confidence: "high", note: "GA isolates the positional-language half of K.G.A.1; the shape-naming half sits in K.GSR.8.1.", reviewed: false },
  { ga: "K.GSR.8.3", ccss: "K.G.B.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.GSR.8.4", ccss: "K.G.B.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.MDR.7.1", ccss: "K.MD.A.2", alt: [], source: "proposed", confidence: "medium", note: "GA merges K.MD.A.1 (describe measurable attributes) with K.MD.A.2 (directly compare) and adds ordering, which CCSS defers to 1.MD.A.1.", reviewed: false },
  { ga: "K.MDR.7.2", ccss: "K.MD.B.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.MDR.7.3", ccss: "1.MD.C.4", alt: [], source: "proposed", confidence: "low", note: "GA introduces statistical questioning and graphical displays in K; CCSS has no K data-display standard, the nearest being 1.MD.C.4.", reviewed: false },
  { ga: "K.NR.1.1", ccss: "K.CC.B.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.1.2", ccss: "K.CC.B.4", alt: [], source: "proposed", confidence: "high", note: "Corresponds specifically to K.CC.B.4b (cardinality); the parent standard is broader.", reviewed: false },
  { ga: "K.NR.1.3", ccss: "K.CC.B.4", alt: [], source: "proposed", confidence: "medium", note: "Matches K.CC.B.4c (one larger) only; CCSS does not state the 'one less' direction, and GA extends the range to 20.", reviewed: false },
  { ga: "K.NR.1.4", ccss: "2.MD.C.8", alt: [], source: "proposed", confidence: "low", note: "GA teaches coin identification and value in K; CCSS has no coin standard before grade 2, and 2.MD.C.8 is a word-problem standard rather than identification.", reviewed: false },
  { ga: "K.NR.2.1", ccss: "K.CC.A.1", alt: [], source: "proposed", confidence: "medium", note: "CCSS covers counting to 100 by ones and tens; the backward counting from 20 has no CCSS analogue.", reviewed: false },
  { ga: "K.NR.2.2", ccss: "K.CC.A.2", alt: [], source: "proposed", confidence: "medium", note: "CCSS covers only counting forward from a given number; GA adds counting backward within 20.", reviewed: false },
  { ga: "K.NR.3.1", ccss: "K.NBT.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.4.1", ccss: "K.CC.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.4.2", ccss: "K.CC.C.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.5.1", ccss: "K.OA.A.3", alt: [], source: "proposed", confidence: "high", note: "GA states composing as well as decomposing; K.OA.A.3 is written as decomposition into pairs.", reviewed: false },
  { ga: "K.NR.5.2", ccss: "K.OA.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.5.3", ccss: "K.OA.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.NR.5.4", ccss: "K.OA.A.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "K.PAR.6.1", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "CCSS omits repeating patterns in K-2 entirely; the only pattern-generation standard is 4.OA.C.5, which is rule-based rather than repeating-core based.", reviewed: false },
  { ga: "K.PAR.6.2", ccss: null, alt: [], source: "proposed", confidence: "low", note: "No CCSSM analogue; patterns in the passage of time are not addressed anywhere in CCSSM.", reviewed: false },
  { ga: "1.GSR.4.1", ccss: "1.G.A.1", alt: [], source: "proposed", confidence: "high", note: "GA adds explicit identification and sorting of named 2D shapes and 3D figures on top of the defining-attribute focus of 1.G.A.1.", reviewed: false },
  { ga: "1.GSR.4.2", ccss: "1.G.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.GSR.4.3", ccss: "1.G.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.MDR.6.1", ccss: "1.MD.A.2", alt: [], source: "proposed", confidence: "medium", note: "GA merges 1.MD.A.1 (order three objects by length) with 1.MD.A.2 (iterate non-standard length units) and adds estimation.", reviewed: false },
  { ga: "1.MDR.6.2", ccss: "1.MD.B.3", alt: [], source: "proposed", confidence: "high", note: "GA adds elapsed time to the hour on a number line, which CCSS does not address until grade 3 (3.MD.A.1).", reviewed: false },
  { ga: "1.MDR.6.3", ccss: "2.MD.C.8", alt: [], source: "proposed", confidence: "low", note: "GA introduces quarters and coin-value comparison in grade 1; CCSS addresses coin values only at grade 2, and there as word problems.", reviewed: false },
  { ga: "1.MDR.6.4", ccss: "1.MD.C.4", alt: [], source: "proposed", confidence: "medium", note: "GA frames the standard around asking questions and comparing/ordering whole numbers; CCSS frames it around organizing and interpreting categorical data.", reviewed: false },
  { ga: "1.NR.1.1", ccss: "1.NBT.A.1", alt: [], source: "proposed", confidence: "high", note: "GA adds counting backward and starting at any number; CCSS states counting forward from any number.", reviewed: false },
  { ga: "1.NR.1.2", ccss: "1.NBT.B.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.1.3", ccss: "1.NBT.B.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.2.1", ccss: "1.OA.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.2.2", ccss: "1.OA.C.6", alt: [], source: "proposed", confidence: "medium", note: "GA's 'strings of related problems' approach maps to the strategy list in 1.OA.C.6; the fluency expectation itself is carried by 1.NR.2.4.", reviewed: false },
  { ga: "1.NR.2.3", ccss: "1.OA.B.4", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.2.4", ccss: "1.OA.C.6", alt: [], source: "proposed", confidence: "high", note: "Matches the 'demonstrating fluency for addition and subtraction within 10' clause of 1.OA.C.6; GA splits that standard across 1.NR.2.2 and 1.NR.2.4.", reviewed: false },
  { ga: "1.NR.2.5", ccss: "1.OA.D.7", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.2.6", ccss: "1.OA.D.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.2.7", ccss: "1.OA.B.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.5.1", ccss: "1.NBT.C.4", alt: [], source: "proposed", confidence: "medium", note: "CCSS grade 1 covers addition within 100 only; general two-digit subtraction within 100 is deferred to 2.NBT.B.5.", reviewed: false },
  { ga: "1.NR.5.2", ccss: "1.NBT.C.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "1.NR.5.3", ccss: "1.NBT.C.6", alt: [], source: "proposed", confidence: "medium", note: "1.NBT.C.6 covers only subtracting multiples of 10; the addition half of the GA expectation falls under 1.NBT.C.4.", reviewed: false },
  { ga: "1.PAR.3.1", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "CCSS has no K-2 repeating-pattern standard; 4.OA.C.5 is the nearest pattern-generation standard and sits three grades later.", reviewed: false },
  { ga: "1.PAR.3.2", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "Growing/shrinking patterns by repeated addition map loosely to 4.OA.C.5; the skip-counting by 2s, 5s and 10s component is closer to 2.NBT.A.2.", reviewed: false },
  { ga: "2.GSR.7.1", ccss: "2.G.A.1", alt: [], source: "proposed", confidence: "high", note: "GA names rectangular prisms and cones among the 3-D figures; CCSSM 2.G.A.1 names cubes.", reviewed: false },
  { ga: "2.GSR.7.2", ccss: "4.G.A.3", alt: [], source: "proposed", confidence: "medium", note: "CCSSM introduces line symmetry in grade 4; GA moves an informal version of it to grade 2.", reviewed: false },
  { ga: "2.GSR.7.3", ccss: "2.G.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.GSR.7.4", ccss: "2.G.A.3", alt: [], source: "proposed", confidence: "high", note: "This is the closing clause of 2.G.A.3 ('recognize that equal shares of identical wholes need not have the same shape'); GA splits 2.G.A.3 across 2.GSR.7.3 and 2.GSR.7.4.", reviewed: false },
  { ga: "2.MDR.5.1", ccss: "1.MD.A.2", alt: [], source: "proposed", confidence: "low", note: "CCSSM has no standard on constructing measuring instruments; the nearest idea is unit iteration (laying copies of a length unit end to end) at grade 1, with ruler use itself at 2.MD.A.1.", reviewed: false },
  { ga: "2.MDR.5.2", ccss: "2.MD.A.1", alt: [], source: "proposed", confidence: "high", note: "GA merges measuring with appropriate tools (2.MD.A.1) and estimating lengths (2.MD.A.3).", reviewed: false },
  { ga: "2.MDR.5.3", ccss: "2.MD.A.4", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.MDR.5.4", ccss: "2.MD.D.10", alt: [], source: "proposed", confidence: "medium", note: "GA frames a full statistical-question cycle (ask, gather, display, answer); CCSSM's nearest grade-2 content is drawing and interpreting picture/bar graphs (2.MD.D.10), with data generation at 2.MD.D.9.", reviewed: false },
  { ga: "2.MDR.5.5", ccss: "2.MD.B.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.MDR.6.1", ccss: "2.MD.C.7", alt: [], source: "proposed", confidence: "high", note: "The telling/writing-time half matches 2.MD.C.7; CCSSM has no elapsed-time standard at grade 2 (elapsed time first appears at 3.MD.A.1).", reviewed: false },
  { ga: "2.MDR.6.2", ccss: "2.MD.C.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.1.1", ccss: "2.NBT.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.1.2", ccss: "2.NBT.A.2", alt: [], source: "proposed", confidence: "high", note: "GA adds counting backward and counting by 25s, which CCSSM 2.NBT.A.2 does not include.", reviewed: false },
  { ga: "2.NR.1.3", ccss: "2.NBT.A.4", alt: [], source: "proposed", confidence: "high", note: "Comparison with >, =, < is 2.NBT.A.4; the 'represent' (read/write, expanded form) portion is 2.NBT.A.3.", reviewed: false },
  { ga: "2.NR.2.1", ccss: "2.OA.B.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.2.2", ccss: "2.NBT.B.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.2.3", ccss: "2.OA.A.1", alt: [], source: "proposed", confidence: "high", note: "Word-problem framing matches 2.OA.A.1; the underlying two-digit computation is 2.NBT.B.5/B.6.", reviewed: false },
  { ga: "2.NR.2.4", ccss: "2.NBT.B.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.3.1", ccss: "2.OA.C.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "2.NR.3.2", ccss: "2.OA.C.4", alt: [], source: "proposed", confidence: "high", note: "GA text is truncated; the full expectation (rectangular arrays, sum of equal addends) is 2.OA.C.4.", reviewed: false },
  { ga: "2.PAR.4.1", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "CCSSM has no patterning standard at grade 2; the closest analogue is generating a pattern from a given rule at grade 4.", reviewed: false },
  { ga: "2.PAR.4.2", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "CCSSM has no growing/shrinking pattern standard at grade 2; nearest analogue is 4.OA.C.5, shared with 2.PAR.4.1.", reviewed: false },
  { ga: "3.GSR.6.1", ccss: "4.G.A.1", alt: [], source: "proposed", confidence: "medium", note: "CCSSM introduces parallel/perpendicular segments and right angles in grade 4; GA moves them to grade 3.", reviewed: false },
  { ga: "3.GSR.6.2", ccss: "3.G.A.1", alt: [], source: "proposed", confidence: "high", note: "The quadrilateral-classification half matches 3.G.A.1; identifying quadrilaterals as faces of 3-D figures has no CCSSM grade-3 analogue.", reviewed: false },
  { ga: "3.GSR.6.3", ccss: "4.G.A.3", alt: [], source: "proposed", confidence: "medium", note: "Line symmetry is a grade-4 topic in CCSSM.", reviewed: false },
  { ga: "3.GSR.7.1", ccss: "3.MD.C.5", alt: [], source: "proposed", confidence: "high", note: "Matches the unit-square/no-gaps-or-overlaps concept of area in 3.MD.C.5 (esp. 3.MD.C.5b).", reviewed: false },
  { ga: "3.GSR.7.2", ccss: "3.MD.C.6", alt: [], source: "proposed", confidence: "high", note: "Areas by counting unit squares is 3.MD.C.6; the 'shapes composed of rectangles' extension is 3.MD.C.7d.", reviewed: false },
  { ga: "3.GSR.7.3", ccss: "3.MD.C.7", alt: [], source: "proposed", confidence: "high", note: "Specifically 3.MD.C.7a-b (tiling shows area equals the product of the side lengths).", reviewed: false },
  { ga: "3.GSR.8.1", ccss: "3.MD.D.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.GSR.8.2", ccss: "3.MD.D.8", alt: [], source: "proposed", confidence: "high", note: "Same-perimeter/different-area comparison is the second half of 3.MD.D.8, which GA splits across 3.GSR.8.1 and 3.GSR.8.2.", reviewed: false },
  { ga: "3.MDR.5.1", ccss: "3.MD.B.3", alt: [], source: "proposed", confidence: "medium", note: "GA frames a full statistical-question cycle; CCSSM's nearest grade-3 content is scaled picture/bar graphs (3.MD.B.3), with line plots at 3.MD.B.4.", reviewed: false },
  { ga: "3.MDR.5.2", ccss: "3.MD.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.MDR.5.3", ccss: "3.MD.A.1", alt: [], source: "proposed", confidence: "high", note: "Elapsed time is the second half of 3.MD.A.1, shared with 3.MDR.5.2; CCSSM's version is not restricted to hour/half-hour/quarter-hour endpoints.", reviewed: false },
  { ga: "3.MDR.5.4", ccss: "3.MD.B.4", alt: [], source: "proposed", confidence: "medium", note: "CCSSM embeds ruler measurement to halves and fourths of an inch inside the line-plot standard; GA states it as a standalone measurement skill.", reviewed: false },
  { ga: "3.MDR.5.5", ccss: "3.MD.A.2", alt: [], source: "proposed", confidence: "high", note: "CCSSM 3.MD.A.2 specifies metric units (g, kg, l); GA specifies customary units and adds length.", reviewed: false },
  { ga: "3.NR.1.1", ccss: "4.NBT.A.2", alt: [], source: "proposed", confidence: "medium", note: "CCSSM caps grade-3 place value at 1000 (2.NBT.A.3 covers base-ten numerals and expanded form to 1000); reading/writing multi-digit numbers in expanded form beyond 1000 is grade 4.", reviewed: false },
  { ga: "3.NR.1.2", ccss: "4.NBT.A.2", alt: [], source: "proposed", confidence: "medium", note: "Comparison to 10,000 exceeds CCSSM grade 3 (2.NBT.A.4 compares to 1000); 4.NBT.A.2 is the multi-digit comparison standard, shared with 3.NR.1.1.", reviewed: false },
  { ga: "3.NR.1.3", ccss: "3.NBT.A.1", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.NR.4.1", ccss: "3.NF.A.1", alt: [], source: "proposed", confidence: "high", note: "Unit-fraction meaning is 3.NF.A.1; the number-line representations GA folds in are 3.NF.A.2.", reviewed: false },
  { ga: "3.NR.4.2", ccss: "3.NF.A.3", alt: [], source: "proposed", confidence: "high", note: "Specifically 3.NF.A.3d (comparing fractions with the same numerator or denominator), narrowed by GA to unit fractions.", reviewed: false },
  { ga: "3.NR.4.3", ccss: "3.NF.A.2", alt: [], source: "proposed", confidence: "medium", note: "GA's 'multiple ways' spans 3.NF.A.1-A.3; the number-line representation is 3.NF.A.2 and whole numbers as fractions is 3.NF.A.3c. CCSSM grade 3 limits fractions greater than one only implicitly.", reviewed: false },
  { ga: "3.NR.4.4", ccss: "3.NF.A.3", alt: [], source: "proposed", confidence: "high", note: "Specifically 3.NF.A.3b ('recognize and generate simple equivalent fractions').", reviewed: false },
  { ga: "3.PAR.2.1", ccss: "3.NBT.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.PAR.2.2", ccss: "3.OA.D.8", alt: [], source: "proposed", confidence: "medium", note: "The equation-with-a-letter framing is 3.OA.D.8; addition/subtraction within 10,000 exceeds CCSSM grade 3 (3.NBT.A.2 caps at 1000; multi-digit fluency is 4.NBT.B.4).", reviewed: false },
  { ga: "3.PAR.3.1", ccss: "3.OA.D.9", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.PAR.3.2", ccss: "3.OA.C.7", alt: [], source: "proposed", confidence: "medium", note: "GA combines strategy-based multiplication/division facts (3.OA.C.7) with understanding division as an unknown-factor problem (3.OA.B.6) and the meanings of the operations (3.OA.A.1-A.2).", reviewed: false },
  { ga: "3.PAR.3.3", ccss: "3.OA.B.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.PAR.3.4", ccss: "1.OA.D.7", alt: [], source: "proposed", confidence: "low", note: "CCSSM addresses the meaning of the equal sign at grade 1 and only for addition/subtraction; GA extends it to multiplication expressions at grade 3.", reviewed: false },
  { ga: "3.PAR.3.5", ccss: "3.NBT.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.PAR.3.6", ccss: "3.OA.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "3.PAR.3.7", ccss: "3.OA.D.8", alt: [], source: "proposed", confidence: "medium", note: "The letter-for-unknown representation is 3.OA.D.8 (shared with 3.PAR.2.2); determining an unknown in an equation is 3.OA.A.4.", reviewed: false },
  { ga: "4.GSR.7.1", ccss: "4.G.A.1", alt: ["4.MD.C.5"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.GSR.7.2", ccss: "4.MD.C.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "4.GSR.8.1", ccss: "4.G.A.1", alt: [], source: "proposed", confidence: "high", note: "CCSSM 4.G.A.1 covers the points/lines/rays/angles/parallel-perpendicular draw-and-identify work; the lines-of-symmetry portion of the Georgia expectation belongs to 4.G.A.3.", reviewed: false },
  { ga: "4.GSR.8.2", ccss: "4.G.A.2", alt: [], source: "proposed", confidence: "high", note: "Classification by parallel/perpendicular sides and angle size is 4.G.A.2; the lines-of-symmetry criterion is 4.G.A.3.", reviewed: false },
  { ga: "4.GSR.8.3", ccss: "3.MD.C.7", alt: ["4.MD.A.3"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.MDR.6.1", ccss: "4.MD.A.2", alt: [], source: "proposed", confidence: "high", note: "Word-problem solving matches 4.MD.A.2; the unit-expression component also draws on 4.MD.A.1, and Georgia adds the smaller-unit-to-larger-unit direction, which CCSSM does not require at grade 4.", reviewed: false },
  { ga: "4.MDR.6.2", ccss: "3.MD.B.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.MDR.6.3", ccss: "4.MD.B.4", alt: [], source: "proposed", confidence: "medium", note: "CCSSM 4.MD.B.4 requires line plots of measurements in fractions of a unit (1/2, 1/4, 1/8) plus fraction add/subtract from the plot; Georgia asks only for dot plots of numerical measurement data.", reviewed: false },
  { ga: "4.NR.1.1", ccss: "4.NBT.A.2", alt: [], source: "proposed", confidence: "high", note: "Maps to the read/write half of 4.NBT.A.2; Georgia caps at hundred-thousands (CCSSM goes to 1,000,000) and omits number names.", reviewed: false },
  { ga: "4.NR.1.2", ccss: "4.NBT.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.1.3", ccss: "4.NBT.A.2", alt: [], source: "proposed", confidence: "high", note: "Maps to the compare half of 4.NBT.A.2, which Georgia splits from the read/write half in 4.NR.1.1; Georgia also adds ordering beyond comparing two numbers, and the place-value reasoning draws on 4.NBT.A.1.", reviewed: false },
  { ga: "4.NR.1.4", ccss: "4.NBT.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.2.1", ccss: "4.NBT.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.2.2", ccss: "4.OA.A.2", alt: [], source: "proposed", confidence: "high", note: "Solving multiplicative-comparison problems is 4.OA.A.2; the interpret/model component corresponds to 4.OA.A.1.", reviewed: false },
  { ga: "4.NR.2.3", ccss: "3.OA.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.2.4", ccss: "4.NBT.B.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "4.NR.2.5", ccss: "4.OA.A.3", alt: [], source: "proposed", confidence: "high", note: "CCSSM 4.OA.A.3 additionally requires representing problems with a letter for the unknown and interpreting remainders; Georgia foregrounds mental computation and estimation.", reviewed: false },
  { ga: "4.NR.4.1", ccss: "4.NF.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.4.2", ccss: "3.NF.A.3d", alt: [], source: "proposed", confidence: "high", note: "Near-verbatim CCSSM 3.NF.A.3d, one grade lower: Georgia places same-numerator/same-denominator comparison at grade 4. Comparison of fractions with unlike numerators AND denominators (4.NF.A.2) is deferred to Georgia grade 5.", reviewed: false },
  { ga: "4.NR.4.3", ccss: "4.NF.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.4.4", ccss: "4.NF.B.3", alt: [], source: "proposed", confidence: "high", note: "Matches the lead statement of 4.NF.B.3 (a/b as a sum of 1/b); decomposing whole numbers into unit fractions is a Georgia extension of that idea.", reviewed: false },
  { ga: "4.NR.4.5", ccss: "4.NF.B.3b", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "4.NR.4.6", ccss: "4.NF.B.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.NR.5.1", ccss: "4.NF.C.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "4.NR.5.2", ccss: "4.NF.C.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "4.NR.5.3", ccss: "4.NF.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "4.PAR.3.1", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "high", note: "Georgia covers only the generate-from-a-rule half; the 'identify apparent features not explicit in the rule' half of 4.OA.C.5 is carried by 4.PAR.3.2.", reviewed: false },
  { ga: "4.PAR.3.2", ccss: "4.OA.C.5", alt: [], source: "proposed", confidence: "low", note: "CCSSM has no grade-4 input-output/function-table standard; the closest analogue is the pattern-analysis half of 4.OA.C.5 (also matched by 4.PAR.3.1). The table representation anticipates 5.OA.B.3.", reviewed: false },
  { ga: "4.PAR.3.3", ccss: "4.OA.B.4", alt: [], source: "proposed", confidence: "high", note: "Georgia splits 4.OA.B.4 in two: factor pairs and multiples here, prime/composite in 4.PAR.3.4.", reviewed: false },
  { ga: "4.PAR.3.4", ccss: "4.OA.B.4", alt: [], source: "proposed", confidence: "high", note: "Prime/composite half of 4.OA.B.4; the factor-pair and multiple half is Georgia 4.PAR.3.3.", reviewed: false },
  { ga: "5.GSR.8.1", ccss: "5.G.B.4", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "5.GSR.8.2", ccss: "5.G.B.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "5.GSR.8.3", ccss: "5.MD.C.5a", alt: [], source: "proposed", confidence: "high", note: "Packing right rectangular prisms with unit cubes and solving volume problems is 5.MD.C.5a; the 'without gaps or overlaps' unit-of-volume idea is 5.MD.C.3b and the counting-unit-cubes measurement is 5.MD.C.4.", reviewed: false },
  { ga: "5.GSR.8.4", ccss: "5.MD.C.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.MDR.7.1", ccss: "5.MD.A.1", alt: [], source: "proposed", confidence: "low", note: "Georgia 5.MDR.7.1 is an exploratory foundation across distance, mass, weight, volume and time rather than a conversion standard; 5.MD.A.1 is the nearest CCSSM home, and weight/mass exploration also echoes 4.MD.A.1.", reviewed: false },
  { ga: "5.MDR.7.2", ccss: "5.MD.B.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.MDR.7.3", ccss: "5.MD.A.1", alt: [], source: "proposed", confidence: "high", note: "5.MD.A.1 covers conversion within any one system; Georgia splits it into metric (5.MDR.7.3) and customary (5.MDR.7.4).", reviewed: false },
  { ga: "5.MDR.7.4", ccss: "5.MD.A.1", alt: [], source: "proposed", confidence: "medium", note: "Customary-system half of 5.MD.A.1 (shared with 5.MDR.7.3); the 'relative sizes of measurement units' framing is CCSSM 4.MD.A.1 language, and Georgia omits the multi-step problem solving here.", reviewed: false },
  { ga: "5.NR.1.1", ccss: "5.NBT.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.1.2", ccss: "5.NBT.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.2.1", ccss: "5.NBT.B.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.2.2", ccss: "5.NBT.B.6", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.3.1", ccss: "5.NF.B.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.3.2", ccss: "4.NF.A.2", alt: [], source: "proposed", confidence: "medium", note: "CCSSM places unlike-numerator/unlike-denominator comparison at grade 4; Georgia moves it to grade 5 and extends it from two fractions to ordering up to three.", reviewed: false },
  { ga: "5.NR.3.3", ccss: "5.NF.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.3.4", ccss: "4.NF.B.4", alt: [], source: "proposed", confidence: "medium", note: "CCSSM treats multiplication of a fraction by a whole number at grade 4 (4.NF.B.4, word problems at 4.NF.B.4c); Georgia places it at grade 5, where the CCSSM problem-solving analogue is 5.NF.B.6.", reviewed: false },
  { ga: "5.NR.3.5", ccss: "5.NF.B.5b", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "5.NR.3.6", ccss: "5.NF.B.7", alt: [], source: "proposed", confidence: "high", note: "Spans 5.NF.B.7a (unit fraction divided by whole number), 5.NF.B.7b (whole number divided by unit fraction) and 5.NF.B.7c (problem solving).", reviewed: false },
  { ga: "5.NR.4.1", ccss: "5.NBT.A.3a", alt: [], source: "proposed", confidence: "high", note: "Georgia asks for standard and expanded form only; CCSSM 5.NBT.A.3a also requires number names.", reviewed: false },
  { ga: "5.NR.4.2", ccss: "5.NBT.A.3b", alt: [], source: "proposed", confidence: "high", note: "CCSSM 5.NBT.A.3b compares two decimals; Georgia adds representing and ordering, and the place-value meaning draws on 5.NBT.A.1.", reviewed: false },
  { ga: "5.NR.4.3", ccss: "5.NBT.A.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.4.4", ccss: "5.NBT.B.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.NR.5.1", ccss: "5.OA.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "5.PAR.6.1", ccss: "5.OA.B.3", alt: [], source: "proposed", confidence: "high", note: "Georgia keeps the generate-two-patterns and table half here; the form-ordered-pairs-and-graph half of 5.OA.B.3 is carried by 5.PAR.6.2.", reviewed: false },
  { ga: "5.PAR.6.2", ccss: "5.G.A.2", alt: [], source: "proposed", confidence: "high", note: "Plotting and interpreting first-quadrant points is 5.G.A.2; understanding the coordinate system itself is 5.G.A.1, and the ordered-pair/graphing half of 5.OA.B.3 also lands here.", reviewed: false },
  { ga: "6.GSR.5.1", ccss: "6.G.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.GSR.5.2", ccss: "6.G.A.4", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.GSR.5.3", ccss: "6.G.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.NR.1.1", ccss: "5.NF.A.1", alt: [], source: "proposed", confidence: "medium", note: "Grade shift: CCSSM places addition/subtraction of fractions with unlike denominators in grade 5; Georgia 2021 revisits it in grade 6 as a fluency expectation, so the match is one grade below the Georgia code.", reviewed: false },
  { ga: "6.NR.1.2", ccss: "5.NF.B.4", alt: ["6.NS.A.1"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.1.3", ccss: "6.NS.B.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.2.1", ccss: "6.SP.B.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.2.2", ccss: "6.SP.B.4", alt: [], source: "proposed", confidence: "medium", note: "6.SP.B.4 covers only the quantitative displays (dot plots, histograms, box plots). The categorical bar-graph half of the Georgia expectation has no grade-6 CCSSM analogue; its nearest CCSSM home is 3.MD.B.3.", reviewed: false },
  { ga: "6.NR.2.3", ccss: "6.SP.B.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.2.4", ccss: "6.SP.B.5", alt: [], source: "proposed", confidence: "medium", note: "Maps to the summarizing/measures portion of 6.SP.B.5 (esp. 5c). Georgia adds experiment design, data collection from simulations, range as a variability measure, and cross-data-set comparison/prediction, none of which are in 6.SP.B.5; CCSSM instead pairs IQR with mean absolute deviation. Shares 6.SP.B.5 with 6.NR.2.5.", reviewed: false },
  { ga: "6.NR.2.5", ccss: "6.SP.B.5", alt: [], source: "proposed", confidence: "high", note: "Near-verbatim match to 6.SP.B.5d. Shares the parent code 6.SP.B.5 with 6.NR.2.4, which matches 6.SP.B.5c.", reviewed: false },
  { ga: "6.NR.2.6", ccss: "6.SP.A.3", alt: [], source: "proposed", confidence: "low", note: "CCSSM has no standard on the effect of inserting or deleting a data point. 6.SP.A.3 (a measure of center summarizes all values with a single number) is the closest conceptual anchor; the display work also touches 6.SP.B.4.", reviewed: false },
  { ga: "6.NR.3.1", ccss: "6.NS.C.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.NR.3.2", ccss: "6.NS.C.6", alt: [], source: "proposed", confidence: "high", note: "Spans 6.NS.C.6a (opposites, distance from zero) and 6.NS.C.6c (positioning integers on a number line); 6.NS.C.6 is also the match for 6.NR.3.3, 6.PAR.8.1, and 6.PAR.8.2.", reviewed: false },
  { ga: "6.NR.3.3", ccss: "6.NS.C.6", alt: [], source: "proposed", confidence: "high", note: "Corresponds specifically to 6.NS.C.6a; shares the parent code with 6.NR.3.2, 6.PAR.8.1, and 6.PAR.8.2.", reviewed: false },
  { ga: "6.NR.3.4", ccss: "6.NS.C.7", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 6.NS.C.7a and 7b; shares the parent code with 6.NR.3.6, which matches 6.NS.C.7d.", reviewed: false },
  { ga: "6.NR.3.5", ccss: "6.NS.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.3.6", ccss: "6.NS.C.7", alt: [], source: "proposed", confidence: "high", note: "Corresponds specifically to 6.NS.C.7d; shares the parent code with 6.NR.3.4.", reviewed: false },
  { ga: "6.NR.4.1", ccss: "6.RP.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.2", ccss: "6.RP.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.3", ccss: "6.RP.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.4", ccss: "6.RP.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.5", ccss: "6.RP.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.6", ccss: "6.RP.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.NR.4.7", ccss: "6.RP.A.3", alt: [], source: "proposed", confidence: "high", note: "Matches the measurement-conversion component 6.RP.A.3d rather than the whole of 6.RP.A.3.", reviewed: false },
  { ga: "6.PAR.6.1", ccss: "6.EE.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.6.2", ccss: "6.NS.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.6.3", ccss: "6.EE.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.6.4", ccss: "6.EE.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.6.5", ccss: "6.EE.A.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.7.1", ccss: "6.EE.B.5", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.PAR.7.2", ccss: "6.EE.B.6", alt: [], source: "proposed", confidence: "medium", note: "6.EE.B.6 carries the variable-meaning language (unknown number or any number in a specified set). The write-and-solve-to-represent-problems half is CCSSM 6.EE.B.7 (equations) and 6.EE.B.8 (inequalities), so the Georgia objective spans three CCSSM standards.", reviewed: false },
  { ga: "6.PAR.7.3", ccss: "6.EE.B.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "6.PAR.7.4", ccss: "6.EE.B.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.PAR.8.1", ccss: "6.NS.C.6", alt: [], source: "proposed", confidence: "high", note: "Corresponds specifically to 6.NS.C.6c; shares the parent code with 6.NR.3.2, 6.NR.3.3, and 6.PAR.8.2.", reviewed: false },
  { ga: "6.PAR.8.2", ccss: "6.NS.C.6", alt: [], source: "proposed", confidence: "high", note: "Corresponds specifically to 6.NS.C.6b; shares the parent code with 6.NR.3.2, 6.NR.3.3, and 6.PAR.8.1.", reviewed: false },
  { ga: "6.PAR.8.3", ccss: "6.NS.C.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "6.PAR.8.4", ccss: "6.G.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.GSR.5.1", ccss: "4.MD.C.5", alt: [], source: "proposed", confidence: "medium", note: "Georgia moves introductory angle measurement to grade 7; CCSSM 4.MD.C.5 develops angle measure as iteration of a unit angle, but frames that unit as the one-degree angle rather than non-standard units, so the non-standard-unit element has no exact CCSSM analogue.", reviewed: false },
  { ga: "7.GSR.5.2", ccss: "4.MD.C.6", alt: [], source: "proposed", confidence: "high", note: "Same expectation (measure whole-number degrees with a protractor) but placed at grade 4 in CCSSM.", reviewed: false },
  { ga: "7.GSR.5.3", ccss: "7.G.B.5", alt: ["8.G.A.5"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.GSR.5.4", ccss: "7.G.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.GSR.5.5", ccss: "7.G.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.GSR.5.6", ccss: "7.G.B.6", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.GSR.5.7", ccss: "7.G.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.GSR.5.8", ccss: "7.G.B.6", alt: [], source: "proposed", confidence: "medium", note: "Splits across CCSSM: right-prism volume is 7.G.B.6, but cylinder volume is 8.G.C.9. Matched to 7.G.B.6 as the primary analogue.", reviewed: false },
  { ga: "7.NR.1.1", ccss: "7.NS.A.1", alt: [], source: "proposed", confidence: "high", note: "Corresponds to sub-standards 7.NS.A.1a and 7.NS.A.1b (opposite quantities combining to make 0; additive inverses).", reviewed: false },
  { ga: "7.NR.1.2", ccss: "7.NS.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.NR.1.3", ccss: "7.NS.A.1", alt: [], source: "proposed", confidence: "high", note: "Also maps to 7.NS.A.1 (number-line representation of rational addition/subtraction, 1b-1d); 7.NR.1.1 and 7.NR.1.3 together cover this one CCSSM standard.", reviewed: false },
  { ga: "7.NR.1.4", ccss: "7.NS.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.NR.1.5", ccss: "7.NS.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.NR.1.6", ccss: "7.NS.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.NR.1.7", ccss: "7.NS.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.NR.1.8", ccss: "7.NS.A.2", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 7.NS.A.2a and 7.NS.A.2b (multiplying and dividing integers/rationals and interpreting products and quotients in context).", reviewed: false },
  { ga: "7.NR.1.9", ccss: "7.NS.A.2", alt: [], source: "proposed", confidence: "high", note: "Specifically 7.NS.A.2c; Georgia splits 7.NS.A.2 across 7.NR.1.8, 7.NR.1.9 and 7.NR.1.10.", reviewed: false },
  { ga: "7.NR.1.10", ccss: "7.NS.A.2", alt: [], source: "proposed", confidence: "medium", note: "Matches 7.NS.A.2d (decimal form terminates or repeats). Georgia additionally requires conversion to and from percentages, which CCSSM treats under 6.RP.A.3c rather than 7.NS.", reviewed: false },
  { ga: "7.NR.1.11", ccss: "7.EE.B.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.PAR.2.1", ccss: "7.EE.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.2.2", ccss: "7.EE.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.PAR.3.1", ccss: "7.EE.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.3.2", ccss: "7.EE.B.4", alt: [], source: "proposed", confidence: "high", note: "Matches the inequality half of the standard (7.EE.B.4b); the equation form px + q = r is 7.EE.B.4a and is covered by a different Georgia objective.", reviewed: false },
  { ga: "7.PAR.4.1", ccss: "7.RP.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.4.2", ccss: "7.RP.A.2", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 7.RP.A.2b (identify the constant of proportionality in tables, graphs, equations, diagrams, and verbal descriptions).", reviewed: false },
  { ga: "7.PAR.4.3", ccss: "7.RP.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.4.4", ccss: "7.RP.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.4.5", ccss: "7.RP.A.2", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 7.RP.A.2d (explain what a point (x, y) means, with attention to (0, 0) and (1, r)).", reviewed: false },
  { ga: "7.PAR.4.6", ccss: "7.G.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.4.7", ccss: "8.EE.B.6", alt: [], source: "proposed", confidence: "high", note: "Georgia moves this slope-similarity argument down to grade 7; CCSSM places it in grade 8.", reviewed: false },
  { ga: "7.PAR.4.8", ccss: "8.EE.B.5", alt: [], source: "proposed", confidence: "high", note: "Georgia moves graphing proportional relationships as slope, and comparing two such relationships in different representations, down to grade 7; CCSSM places it in grade 8.", reviewed: false },
  { ga: "7.PAR.4.9", ccss: "7.RP.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PAR.4.10", ccss: "7.SP.A.1", alt: [], source: "proposed", confidence: "high", note: "Georgia splits 7.SP.A.1 into two objectives; this one covers using a representative sample to generalize to the population and the limits of that generalization.", reviewed: false },
  { ga: "7.PAR.4.11", ccss: "7.SP.A.1", alt: [], source: "proposed", confidence: "high", note: "Covers the random-sampling clause of the same CCSSM standard matched by 7.PAR.4.10.", reviewed: false },
  { ga: "7.PAR.4.12", ccss: "7.SP.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.PR.6.1", ccss: "7.SP.C.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PR.6.2", ccss: "7.SP.C.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "7.PR.6.3", ccss: "7.SP.C.7", alt: ["7.SP.C.8"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PR.6.4", ccss: "7.SP.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "7.PR.6.5", ccss: "7.SP.C.7", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 7.SP.C.7b (develop a probability model, possibly non-uniform, from observed frequencies).", reviewed: false },
  { ga: "7.PR.6.6", ccss: "7.SP.B.4", alt: [], source: "proposed", confidence: "medium", note: "CCSSM 7.SP.B.4 uses measures of center and variability to draw informal comparative inferences about two populations; Georgia broadens this to graphical displays and to categorical variables, and frames the displays as probability models, so the match is partial. The graphical-display element also touches 7.SP.B.3.", reviewed: false },
  { ga: "8.FGR.5.1", ccss: "8.F.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.5.2", ccss: "8.F.A.3", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.5.3", ccss: "HSF.IF.B.5", alt: [], source: "proposed", confidence: "high", note: "Georgia moved this HS Functions expectation down to grade 8; wording is verbatim F-IF.5 but restricted to linear functions.", reviewed: false },
  { ga: "8.FGR.5.4", ccss: "8.F.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.FGR.5.5", ccss: "8.F.A.3", alt: ["8.F.B.4"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.5.6", ccss: "HSF.IF.C.8", alt: [], source: "proposed", confidence: "medium", note: "F-IF.8 is an HS standard whose exemplars are quadratic/exponential; Georgia applies the same 'equivalent forms reveal properties' idea to linear functions only.", reviewed: false },
  { ga: "8.FGR.5.7", ccss: "8.EE.B.6", alt: ["8.F.B.4"], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.5.8", ccss: "8.F.B.4", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.5.9", ccss: "HSF.IF.C.7", alt: [], source: "proposed", confidence: "medium", note: "Matches F-IF.7a (graph linear functions, show intercepts) at HS; grade-8 8.F.B.4 covers only part of the intent (rate of change and initial value).", reviewed: false },
  { ga: "8.FGR.6.1", ccss: "8.SP.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.FGR.6.2", ccss: "8.SP.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.FGR.6.3", ccss: "HSS.ID.C.7", alt: [], source: "proposed", confidence: "high", note: "Wording ('predicted slope / rate of change', 'constant term') tracks HS S-ID.7; overlaps the interpretive half of 8.SP.A.3, which is matched by 8.FGR.6.2.", reviewed: false },
  { ga: "8.FGR.6.4", ccss: "8.SP.A.2", alt: [], source: "proposed", confidence: "low", note: "Partial: 8.SP.A.2 covers informally fitting a straight line; Georgia's added framing (graphical displays of data distributions, informal inferences, statistical investigative question, unbiased study) spans 8.SP.A.1 and 7.SP.A.1-2 and has no single CCSSM analogue.", reviewed: false },
  { ga: "8.FGR.7.1", ccss: "8.EE.C.8", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 8.EE.C.8c (real-world problems leading to two linear equations in two variables).", reviewed: false },
  { ga: "8.FGR.7.2", ccss: "8.EE.C.8", alt: [], source: "proposed", confidence: "high", note: "Corresponds to 8.EE.C.8a (solutions correspond to points of intersection).", reviewed: false },
  { ga: "8.FGR.7.3", ccss: "8.EE.C.8", alt: [], source: "proposed", confidence: "medium", note: "Georgia splits 8.EE.C.8b across two objectives; this one takes the 'estimate solutions by graphing / solve simple cases by inspection' half.", reviewed: false },
  { ga: "8.FGR.7.4", ccss: "8.EE.C.8", alt: [], source: "proposed", confidence: "high", note: "Takes the 'solve systems algebraically' half of 8.EE.C.8b; paired with 8.FGR.7.3.", reviewed: false },
  { ga: "8.FGR.7.5", ccss: "8.EE.C.8", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.GSR.8.1", ccss: "8.G.B.6", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.GSR.8.2", ccss: "8.G.B.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.GSR.8.3", ccss: "8.G.B.8", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.GSR.8.4", ccss: "8.G.C.9", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.NR.1.1", ccss: "8.NS.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.NR.1.2", ccss: "8.NS.A.2", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.NR.2.1", ccss: "8.EE.A.1", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.NR.2.2", ccss: "8.EE.A.2", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.NR.2.3", ccss: "8.EE.A.3", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.NR.2.4", ccss: "8.EE.A.4", alt: [], source: "proposed", confidence: "high", note: null, reviewed: false },
  { ga: "8.PAR.3.1", ccss: "HSA.SSE.A.1", alt: [], source: "proposed", confidence: "medium", note: "Georgia moved HS A-SSE.1 (both a: interpret terms/factors/coefficients, and b: interpret complicated expressions by parts) into grade 8; grade-6 6.EE.A.2b is a weaker partial analogue.", reviewed: false },
  { ga: "8.PAR.3.2", ccss: "8.EE.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.PAR.3.3", ccss: "8.EE.C.7", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.PAR.3.4", ccss: "HSA.REI.A.1", alt: [], source: "proposed", confidence: "medium", note: "A-REI.1 is stated for equations only; Georgia extends the justification requirement to inequalities and is an HS standard placed in grade 8.", reviewed: false },
  { ga: "8.PAR.3.5", ccss: "HSA.REI.B.3", alt: [], source: "proposed", confidence: "high", note: "Verbatim match to the HS standard (coefficients represented by letters), placed by Georgia in grade 8.", reviewed: false },
  { ga: "8.PAR.3.6", ccss: "HSA.CED.A.4", alt: [], source: "proposed", confidence: "medium", note: "Literal-equation manipulation matches HS A-CED.4; the fluency-with-linear-equations portion also overlaps 8.EE.C.7b.", reviewed: false },
  { ga: "8.PAR.4.1", ccss: "8.EE.B.5", alt: [], source: "existing-app-map", confidence: "carried", note: null, reviewed: false },
  { ga: "8.PAR.4.2", ccss: "HSA.REI.D.10", alt: [], source: "proposed", confidence: "high", note: "HS standard placed in grade 8 by Georgia; wording is near-identical to A-REI.10.", reviewed: false },
];
