/**
 * EdKairos - Georgia K-12 Mathematics Standards (2021), grades K-8.
 * GENERATED FILE - do not hand-edit. Regenerate from the GaDOE PDF.
 *
 * Source: "Georgia's K-12 Mathematics Standards - 2021", Georgia Department of
 * Education, August 2021 (K-8 document, 126 pp). Text is verbatim from the
 * "Expectations" column of each grade-level table.
 *
 * 67 grade-level competencies (clusters) - 265 learning objectives (expectations).
 * This file is the single source of truth for what a Georgia standard IS.
 * Every other standards table in the codebase should resolve THROUGH it.
 */

export type GaStrand = 'NR' | 'PAR' | 'GSR' | 'MDR' | 'PR' | 'FGR';

export interface GaCluster {
  /** e.g. "6.NR.4" - Georgia calls this a grade-level competency/standard */
  code: string;
  grade: string;      // "K" | "1" ... "8"
  gradeNum: number;   // K = 0
  strand: GaStrand;
  strandName: string;
  text: string;       // verbatim competency statement
  page: number;       // page in the GaDOE PDF, for citation
}

export interface GaExpectation {
  /** e.g. "6.NR.4.1" - Georgia calls this a learning objective */
  code: string;
  cluster: string;
  grade: string;
  gradeNum: number;
  strand: GaStrand;
  strandName: string;
  text: string;       // verbatim learning objective
  page: number;
}

export const GA_SOURCE = "Georgia's K-12 Mathematics Standards - 2021 (K-8), Georgia Department of Education, August 2021";
export const GA_EXTRACTED_ON = "2026-08-22";

export const GA_STRANDS: Record<string, string> = {
  NR: "Numerical Reasoning",
  PAR: "Patterning & Algebraic Reasoning",
  GSR: "Geometric & Spatial Reasoning",
  MDR: "Measurement & Data Reasoning",
  PR: "Probability Reasoning",
  FGR: "Functional & Graphical Reasoning",
};

export const GA_CLUSTERS: GaCluster[] = [
  { code: "K.GSR.8", grade: "K", gradeNum: 0, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 7,
    text: "Identify, describe, and compare basic shapes encountered in the environment, and form two-dimensional shapes and three-dimensional figures." },
  { code: "K.MDR.7", grade: "K", gradeNum: 0, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 7,
    text: "Observe, describe, and compare the physical and measurable attributes of objects and analyze graphical displays of data to answer relevant questions." },
  { code: "K.NR.1", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 7,
    text: "Demonstrate and explain the relationship between numbers and quantities up to 20; connect counting to cardinality (the last number counted represents the total quantity in a set)." },
  { code: "K.NR.2", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 7,
    text: "Use count sequences within 100 to count forward and backward in sequence." },
  { code: "K.NR.3", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 7,
    text: "Use place value understanding to compose and decompose numbers from 11–19." },
  { code: "K.NR.4", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 7,
    text: "Identify, write, represent, and compare numbers up to 20." },
  { code: "K.NR.5", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 7,
    text: "Explain the concepts of addition, subtraction, and equality and use these concepts to solve real-life problems within 10." },
  { code: "K.PAR.6", grade: "K", gradeNum: 0, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 7,
    text: "Explain, extend, and create repeating patterns with a repetition, not exceeding 4 and describe patterns involving the passage of time." },
  { code: "1.GSR.4", grade: "1", gradeNum: 1, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 16,
    text: "Compose shapes, analyze the attributes of shapes, and relate their parts to the whole." },
  { code: "1.MDR.6", grade: "1", gradeNum: 1, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 16,
    text: "Use appropriate tools to measure, order, and compare intervals of length and time, as well as denominations of money to solve real-life, mathematical problems and analyze graphical displays of data to answer relevant questions." },
  { code: "1.NR.1", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 16,
    text: "Extend the count sequence to 120. Read, write, and represent numerical values to 120 and compare numerical values to 100." },
  { code: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 16,
    text: "Explain the relationship between addition and subtraction and apply the properties of operations to solve real-life addition and subtraction problems within 20." },
  { code: "1.NR.5", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 16,
    text: "Use concrete models, the base ten structure, and properties of operations to add and subtract within 100." },
  { code: "1.PAR.3", grade: "1", gradeNum: 1, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 16,
    text: "Identify, describe, extend, and create repeating patterns, growing patterns, and shrinking patterns found in real-life situations." },
  { code: "2.GSR.7", grade: "2", gradeNum: 2, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 26,
    text: "Draw and partition shapes and other objects with specific attributes, and conduct observations of everyday items and structures to identify how shapes exist in the world." },
  { code: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 26,
    text: "Estimate and measure the lengths of objects and distance to solve problems found in real-life using standard units of measurement, including inches, feet, and yards and analyze graphical displays of data to answer relevant questions." },
  { code: "2.MDR.6", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 26,
    text: "Solve real-life problems involving time and money." },
  { code: "2.NR.1", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 26,
    text: "Using the place value structure, explore the count sequences to represent, read, write, and compare numerical values to 1000 and describe basic place-value relationships and structures." },
  { code: "2.NR.2", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 26,
    text: "Apply multiple part-whole strategies, properties of operations and place value understanding to solve real-life, mathematical problems involving addition and subtraction within 1,000." },
  { code: "2.NR.3", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 26,
    text: "Work with equal groups to gain foundations for multiplication through real-life, mathematical problems." },
  { code: "2.PAR.4", grade: "2", gradeNum: 2, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 26,
    text: "Identify, describe, extend, and create repeating patterns, growing patterns, and shrinking patterns." },
  { code: "3.GSR.6", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 35,
    text: "Identify the attributes of polygons, including parallel segments, perpendicular segments, right angles, and symmetry." },
  { code: "3.GSR.7", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 35,
    text: "Identify area as a measurable attribute of rectangles and determine the area of a rectangle presented in real-life, mathematical problems." },
  { code: "3.GSR.8", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 35,
    text: "Determine the perimeter of a polygon presented in real-life, mathematical problems." },
  { code: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 35,
    text: "Solve real-life, mathematical problems involving length, liquid volume, mass, and time and analyze graphical displays of data to answer relevant questions." },
  { code: "3.NR.1", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 35,
    text: "Use place value reasoning to represent, read, write, and compare numerical values up to 10,000 and round whole numbers up to 1,000." },
  { code: "3.NR.4", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 35,
    text: "Represent fractions with denominators of 2, 3, 4, 6 and 8 in multiple ways within a framework using visual models." },
  { code: "3.PAR.2", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 37,
    text: "Use part-whole strategies to represent and solve real-life problems involving addition and subtraction with whole numbers up to 10,000." },
  { code: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 35,
    text: "Use part-whole strategies to solve real-life, mathematical problems involving multiplication and division with whole numbers within 100." },
  { code: "4.GSR.7", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 45,
    text: "Investigate the concepts of angles and angle measurement to estimate and measure angles." },
  { code: "4.GSR.8", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 45,
    text: "Identify and draw geometric objects, classify polygons based on properties, and solve problems involving area and perimeter of rectangular figures." },
  { code: "4.MDR.6", grade: "4", gradeNum: 4, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 45,
    text: "Measure time and objects that exist in the world to solve real-life, mathematical problems and analyze graphical displays of data to answer relevant questions." },
  { code: "4.NR.1", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 45,
    text: "Recognize patterns within the base ten place value system with quantities presented in real-life situations to compare and round multi-digit whole numbers through the hundred-thousands place." },
  { code: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 45,
    text: "Using part-whole strategies, solve problems involving addition and subtraction through the hundred-thousands place, as well as multiplication and division of multi-digit whole numbers presented in real-life, mathematical situations." },
  { code: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 45,
    text: "Solve real-life problems involving addition, subtraction, equivalence, and comparison of fractions with denominators of 2, 3, 4, 5, 6, 8, 10, 12, and 100 using part-whole strategies and visual models." },
  { code: "4.NR.5", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 45,
    text: "Solve real-life problems involving addition, equivalence, comparison of fractions with denominators of 10 and 100, and comparison of decimal numbers as tenths and hundredths using part- whole strategies and visual models." },
  { code: "4.PAR.3", grade: "4", gradeNum: 4, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 45,
    text: "Generate and analyze patterns, including those involving shapes, input/output diagrams, factors, multiples, prime numbers, and composite numbers." },
  { code: "5.GSR.8", grade: "5", gradeNum: 5, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 61,
    text: "Examine properties of polygons and rectangular prisms, classify polygons by their properties, and discover volume of right rectangular prisms." },
  { code: "5.MDR.7", grade: "5", gradeNum: 5, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 61,
    text: "Solve problems involving customary measurements, metric measurements, and time and analyze graphical displays of data to answer relevant questions." },
  { code: "5.NR.1", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 61,
    text: "Use place value understanding to solve real-life, mathematical problems." },
  { code: "5.NR.2", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 61,
    text: "Multiply and divide multi-digit whole numbers to solve relevant, mathematical problems." },
  { code: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 61,
    text: "Describe fractions and perform operations with fractions to solve relevant, mathematical problems using part-whole strategies and visual models." },
  { code: "5.NR.4", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 61,
    text: "Read, write, and compare decimal numbers to the thousandths place, and round and perform operations with decimal numbers to the hundredths place to solve relevant, mathematical problems." },
  { code: "5.NR.5", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 61,
    text: "Write, interpret, and evaluate numerical expressions within authentic problems." },
  { code: "5.PAR.6", grade: "5", gradeNum: 5, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 61,
    text: "Solve relevant problems by creating and analyzing numerical patterns using the given rule(s)." },
  { code: "6.GSR.5", grade: "6", gradeNum: 6, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 76,
    text: "Solve relevant problems involving area, surface area, and volume." },
  { code: "6.NR.1", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 76,
    text: "Solve relevant, mathematical problems involving operations with whole numbers, fractions, and decimal numbers." },
  { code: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 76,
    text: "Apply operations with whole numbers, fractions and decimals within relevant applications." },
  { code: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 76,
    text: "Solve a variety of problems involving whole numbers and their opposites; model rational numbers on a number line to describe problems presented in relevant, mathematical situations." },
  { code: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 76,
    text: "Solve a variety of contextual problems involving ratios, unit rates, equivalent ratios, percentages, and conversions within measurement systems using proportional reasoning." },
  { code: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 86,
    text: "Identify, write, evaluate, and interpret numerical and algebraic expressions as mathematical models to explain relevant situations." },
  { code: "6.PAR.7", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 76,
    text: "Write and solve one-step equations and inequalities as mathematical models to explain authentic, realistic situations." },
  { code: "6.PAR.8", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 76,
    text: "Graph rational numbers as points on the coordinate plane to represent and solve contextual, mathematical problems; draw polygons using the coordinates for their vertices and find the length of a side of a polygon." },
  { code: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 90,
    text: "Solve practical problems involving angle measurement, circles, area of circles, surface area of prisms and cylinders, and volume of cylinders and prisms composed of cubes and right prisms." },
  { code: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 90,
    text: "Solve relevant, mathematical problems, including multi-step problems, involving the four operations with rational numbers and quantities in any form (integers, percentages, fractions, and decimal numbers)." },
  { code: "7.PAR.2", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 90,
    text: "Use properties of operations, generate equivalent expressions and interpret the expressions to explain relevant situations." },
  { code: "7.PAR.3", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 90,
    text: "Represent authentic situations using equations and inequalities with variables; solve equations and inequalities symbolically, using the properties of equality." },
  { code: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 90,
    text: "Recognize proportional relationships in relevant, mathematical problems; represent, solve, and explain these relationships with tables, graphs, and equations." },
  { code: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 90,
    text: "Using mathematical reasoning, investigate chance processes and develop, evaluate, and use probability models to find probabilities of simple events presented in authentic situations." },
  { code: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 103,
    text: "Describe the properties of functions to define, evaluate, and compare relationships, and use functions and graphs of functions to model and explain real phenomena." },
  { code: "8.FGR.6", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 103,
    text: "Solve practical, linear problems involving situations using bivariate quantitative data." },
  { code: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 103,
    text: "Justify and use various strategies to solve systems of linear equations to model and explain realistic phenomena." },
  { code: "8.GSR.8", grade: "8", gradeNum: 8, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 103,
    text: "Solve contextual, geometric problems involving the Pythagorean Theorem and the volume of geometric figures to explain real phenomena." },
  { code: "8.NR.1", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 103,
    text: "Solve problems involving irrational numbers and rational approximations of irrational numbers to explain realistic applications." },
  { code: "8.NR.2", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 103,
    text: "Solve problems involving radicals and integer exponents including relevant application situations; apply place value understanding with scientific notation and use scientific notation to explain real phenomena." },
  { code: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 103,
    text: "Create and interpret expressions within relevant situations. Create, interpret, and solve linear equations and linear inequalities in one variable to model and explain real phenomena." },
  { code: "8.PAR.4", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 103,
    text: "Show and explain the connections between proportional and non-proportional relationships, lines, and linear equations; create and interpret graphical mathematical models and use the graphical, mathematical model to explain real phenomena represented in the graph." },
];

export const GA_EXPECTATIONS: GaExpectation[] = [
  { code: "K.GSR.8.1", cluster: "K.GSR.8", grade: "K", gradeNum: 0, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 15,
    text: "Identify, sort, classify, analyze, and compare two- dimensional shapes and three-dimensional figures, in different sizes and orientations, using informal language to describe their similarities, differences, number of sides and vertices, and other attributes." },
  { code: "K.GSR.8.2", cluster: "K.GSR.8", grade: "K", gradeNum: 0, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 15,
    text: "Describe the relative location of an object using positional words." },
  { code: "K.GSR.8.3", cluster: "K.GSR.8", grade: "K", gradeNum: 0, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 15,
    text: "Use basic shapes to represent specific shapes found in the environment by creating models and drawings." },
  { code: "K.GSR.8.4", cluster: "K.GSR.8", grade: "K", gradeNum: 0, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 15,
    text: "Use two or more basic shapes to form larger shapes." },
  { code: "K.MDR.7.1", cluster: "K.MDR.7", grade: "K", gradeNum: 0, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 13,
    text: "Directly compare, describe, and order common objects, using measurable attributes (length, height, width, or weight) and describe the difference." },
  { code: "K.MDR.7.2", cluster: "K.MDR.7", grade: "K", gradeNum: 0, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 14,
    text: "Classify and sort up to ten objects into categories by an attribute; count the number of objects in each category and sort the categories by count." },
  { code: "K.MDR.7.3", cluster: "K.MDR.7", grade: "K", gradeNum: 0, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 14,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to solve problems relevant to everyday life." },
  { code: "K.NR.1.1", cluster: "K.NR.1", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 8,
    text: "Count up to 20 objects in a variety of structured arrangements and up to 10 objects in a scattered arrangement." },
  { code: "K.NR.1.2", cluster: "K.NR.1", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 8,
    text: "When counting objects, explain that the last number counted represents the total quantity in a set (cardinality), regardless of the arrangement and order." },
  { code: "K.NR.1.3", cluster: "K.NR.1", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 8,
    text: "Given a number from 1-20, identify the number that is one more or one less." },
  { code: "K.NR.1.4", cluster: "K.NR.1", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 8,
    text: "Identify pennies, nickels, and dimes and know their name and value." },
  { code: "K.NR.2.1", cluster: "K.NR.2", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 9,
    text: "Count forward to 100 by tens and ones and backward from 20 by ones." },
  { code: "K.NR.2.2", cluster: "K.NR.2", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 9,
    text: "Count forward beginning from any number within 100 and count backward from any number within 20." },
  { code: "K.NR.3.1", cluster: "K.NR.3", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 9,
    text: "Describe numbers from 11 to 19 by composing (putting together) and decomposing (breaking apart) the numbers into ten ones and some more ones." },
  { code: "K.NR.4.1", cluster: "K.NR.4", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 10,
    text: "Identify written numerals 0- 20 and represent a number of objects with a written numeral 0-20 (with 0 representing a count of no objects)." },
  { code: "K.NR.4.2", cluster: "K.NR.4", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 10,
    text: "Compare two sets of up to 10 objects and identify whether the number of objects in one group is more or less than the other group, using the words “greater than,” “less than,” or “the same as”." },
  { code: "K.NR.5.1", cluster: "K.NR.5", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 10,
    text: "Compose (put together) and decompose (break apart) numbers up to 10 using objects and drawings." },
  { code: "K.NR.5.2", cluster: "K.NR.5", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 10,
    text: "Represent addition and subtraction within 10 from a given authentic situation using a variety of representations and strategies." },
  { code: "K.NR.5.3", cluster: "K.NR.5", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 11,
    text: "Use a variety of strategies to solve addition and subtraction problems within 10." },
  { code: "K.NR.5.4", cluster: "K.NR.5", grade: "K", gradeNum: 0, strand: "NR", strandName: "Numerical Reasoning", page: 12,
    text: "Fluently add and subtract within 5 using a variety of strategies to solve practical, mathematical problems." },
  { code: "K.PAR.6.1", cluster: "K.PAR.6", grade: "K", gradeNum: 0, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 13,
    text: "Create, extend, and describe repeating patterns with numbers and shapes, and explain the rationale for the pattern." },
  { code: "K.PAR.6.2", cluster: "K.PAR.6", grade: "K", gradeNum: 0, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 13,
    text: "Describe patterns involving the passage of time using words and phrases related to actual events." },
  { code: "1.GSR.4.1", cluster: "1.GSR.4", grade: "1", gradeNum: 1, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 21,
    text: "Identify common two- dimensional shapes and three- dimensional figures, sort and classify them by their attributes and build and draw shapes that possess defining attributes." },
  { code: "1.GSR.4.2", cluster: "1.GSR.4", grade: "1", gradeNum: 1, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 21,
    text: "Compose two-dimensional shapes (rectangles, squares, triangles, half-circles, and quarter-circles) and three-dimensional figures (cubes, rectangular prisms, cones, and cylinders) to create a shape formed of two or more common shapes and compose new shapes from the composite shape." },
  { code: "1.GSR.4.3", cluster: "1.GSR.4", grade: "1", gradeNum: 1, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 22,
    text: "Partition circles and rectangles into two and four equal shares." },
  { code: "1.MDR.6.1", cluster: "1.MDR.6", grade: "1", gradeNum: 1, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 24,
    text: "Estimate, measure, and record lengths of objects using non-standard units, and compare and order up to three objects using the recorded measurements. Describe the objects compared." },
  { code: "1.MDR.6.2", cluster: "1.MDR.6", grade: "1", gradeNum: 1, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 24,
    text: "Tell and write time in hours and half-hours using analog and digital clocks, and measure elapsed time to the hour on the hour using a predetermined number line." },
  { code: "1.MDR.6.3", cluster: "1.MDR.6", grade: "1", gradeNum: 1, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 25,
    text: "Identify the value of quarters and compare the values of pennies, nickels, dimes, and quarters." },
  { code: "1.MDR.6.4", cluster: "1.MDR.6", grade: "1", gradeNum: 1, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 25,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to compare and order whole numbers." },
  { code: "1.NR.1.1", cluster: "1.NR.1", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 17,
    text: "Count within 120, forward and backward, starting at any number. In this range, read and write numerals and represent a number of objects with a written numeral." },
  { code: "1.NR.1.2", cluster: "1.NR.1", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 17,
    text: "Explain that the two digits of a 2-digit number represent the amounts of tens and ones." },
  { code: "1.NR.1.3", cluster: "1.NR.1", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 17,
    text: "Compare and order whole numbers up to 100 using concrete models, drawings, and the symbols >, =, and <." },
  { code: "1.NR.2.1", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 18,
    text: "Use a variety of strategies to solve addition and subtraction problems within 20." },
  { code: "1.NR.2.2", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 18,
    text: "Use pictures, drawings, and equations to develop strategies for addition and subtraction within 20 by exploring strings of related problems." },
  { code: "1.NR.2.3", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 19,
    text: "Recognize the inverse relationship between subtraction and addition within 20 and use this inverse relationship to solve authentic problems." },
  { code: "1.NR.2.4", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 19,
    text: "Fluently add and subtract within 10 using a variety of strategies." },
  { code: "1.NR.2.5", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 19,
    text: "Use the meaning of the equal sign to determine whether equations involving addition and subtraction are true or false." },
  { code: "1.NR.2.6", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 19,
    text: "Determine the unknown whole number in an addition or subtraction equation relating to three whole numbers." },
  { code: "1.NR.2.7", cluster: "1.NR.2", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 19,
    text: "Apply properties of operations as strategies to solve addition and subtraction problem situations within 20." },
  { code: "1.NR.5.1", cluster: "1.NR.5", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 22,
    text: "Use a variety of strategies to solve applicable, mathematical addition and subtraction problems with numbers." },
  { code: "1.NR.5.2", cluster: "1.NR.5", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 23,
    text: "Given a two-digit number, mentally find 10 more or 10 less than the number, without having to count; explain the reasoning used." },
  { code: "1.NR.5.3", cluster: "1.NR.5", grade: "1", gradeNum: 1, strand: "NR", strandName: "Numerical Reasoning", page: 23,
    text: "Add and subtract multiples of 10 within 100." },
  { code: "1.PAR.3.1", cluster: "1.PAR.3", grade: "1", gradeNum: 1, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 20,
    text: "Investigate, create, and make predictions about repeating patterns with a core of up to 3 elements resulting from repeating an operation, as a series of shapes, or a number string." },
  { code: "1.PAR.3.2", cluster: "1.PAR.3", grade: "1", gradeNum: 1, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 20,
    text: "Identify, describe, and create growing, shrinking, and repeating patterns based on the repeated addition or subtraction of 1s, 2s, 5s, and 10s." },
  { code: "2.GSR.7.1", cluster: "2.GSR.7", grade: "2", gradeNum: 2, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 33,
    text: "Describe, compare and sort 2-D shapes including polygons, triangles, quadrilaterals, pentagons, hexagons, and 3-D shapes including rectangular prisms and cones, given a set of attributes." },
  { code: "2.GSR.7.2", cluster: "2.GSR.7", grade: "2", gradeNum: 2, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 33,
    text: "Identify at least one line of symmetry in everyday objects to describe each object as a whole." },
  { code: "2.GSR.7.3", cluster: "2.GSR.7", grade: "2", gradeNum: 2, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 33,
    text: "Partition circles and rectangles into two, three, or four equal shares. Identify and describe equal-sized parts of the whole using fractional names (“halves,” “thirds,” “fourths”, “half of,” “third of,” “quarter of,” etc.)." },
  { code: "2.GSR.7.4", cluster: "2.GSR.7", grade: "2", gradeNum: 2, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 34,
    text: "Recognize that equal shares of identical wholes may be different shapes within the same whole." },
  { code: "2.MDR.5.1", cluster: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 31,
    text: "Construct simple measuring instruments using unit models. Compare unit models to rulers." },
  { code: "2.MDR.5.2", cluster: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 31,
    text: "Estimate and measure the length of an object or distance to the nearest whole unit using appropriate units and standard measuring tools." },
  { code: "2.MDR.5.3", cluster: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 31,
    text: "Measure to determine how much longer one object is than another and express the length difference in terms of a standard-length unit." },
  { code: "2.MDR.5.4", cluster: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 31,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to solve problems relevant to everyday life." },
  { code: "2.MDR.5.5", cluster: "2.MDR.5", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 31,
    text: "Represent whole-number sums and differences within a standard unit of measurement on a number line diagram." },
  { code: "2.MDR.6.1", cluster: "2.MDR.6", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 32,
    text: "Tell and write time from analog and digital clocks to the nearest five minutes, and estimate and measure elapsed time using a timeline, to the hour or half hour on the hour or half hour." },
  { code: "2.MDR.6.2", cluster: "2.MDR.6", grade: "2", gradeNum: 2, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 32,
    text: "Find the value of a group of coins and determine combinations of coins that equal a given amount that is less than one hundred cents, and solve problems involving dollar bills, quarters, dimes, nickels, and pennies, using $ and ¢ symbols appropriately." },
  { code: "2.NR.1.1", cluster: "2.NR.1", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 27,
    text: "Explain the value of a three- digit number using hundreds, tens, and ones in a variety of ways." },
  { code: "2.NR.1.2", cluster: "2.NR.1", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 27,
    text: "Count forward and backward by ones from any number within 1000. Count forward by fives from multiples of 5 within 1000. Count forward and backward by 10s and 100s from any number within 1000. Count forward by 25s from 0." },
  { code: "2.NR.1.3", cluster: "2.NR.1", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 27,
    text: "Represent, compare, and order whole numbers to 1000 with an emphasis on place value and equality. Use >, =, and < symbols to record the results of comparisons." },
  { code: "2.NR.2.1", cluster: "2.NR.2", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 27,
    text: "Fluently add and subtract within 20 using a variety of mental, part-whole strategies." },
  { code: "2.NR.2.2", cluster: "2.NR.2", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 28,
    text: "Find 10 more or 10 less than a given three-digit number and find 100 more or 100 less than a given three-digit number." },
  { code: "2.NR.2.3", cluster: "2.NR.2", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 28,
    text: "Solve problems involving the addition and subtraction of two-digit numbers using part-whole strategies." },
  { code: "2.NR.2.4", cluster: "2.NR.2", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 29,
    text: "Fluently add and subtract within 100 using strategies based on place value, properties of operations, and/or the relationship between addition and subtraction." },
  { code: "2.NR.3.1", cluster: "2.NR.3", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 29,
    text: "Determine whether a group (up to 20) has an odd or even number of objects. Write an equation to express an even number as a sum of two equal addends." },
  { code: "2.NR.3.2", cluster: "2.NR.3", grade: "2", gradeNum: 2, strand: "NR", strandName: "Numerical Reasoning", page: 29,
    text: "Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and up to 5 columns; write an equation to express the total as a sum of equal addends." },
  { code: "2.PAR.4.1", cluster: "2.PAR.4", grade: "2", gradeNum: 2, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 30,
    text: "Identify, describe, and create a numerical pattern resulting from repeating an operation such as addition and subtraction." },
  { code: "2.PAR.4.2", cluster: "2.PAR.4", grade: "2", gradeNum: 2, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 31,
    text: "Identify, describe, and create growing patterns and shrinking patterns involving addition and subtraction up to 20." },
  { code: "3.GSR.6.1", cluster: "3.GSR.6", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 42,
    text: "Identify perpendicular line segments, parallel line segments, and right angles, identify these in polygons, and solve problems involving parallel line segments, perpendicular line segments, and right angles." },
  { code: "3.GSR.6.2", cluster: "3.GSR.6", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 42,
    text: "Classify, compare, and contrast polygons, with a focus on quadrilaterals, based on properties. Analyze specific 3- dimensional figures to identify and describe quadrilaterals as faces of these figures." },
  { code: "3.GSR.6.3", cluster: "3.GSR.6", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 42,
    text: "Identify lines of symmetry in polygons." },
  { code: "3.GSR.7.1", cluster: "3.GSR.7", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 42,
    text: "Investigate area by covering the space of rectangles presented in realistic situations using multiple copies of the same unit, with no gaps or overlaps, and determine the total area (total number of units that covered the space)." },
  { code: "3.GSR.7.2", cluster: "3.GSR.7", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 43,
    text: "Determine the area of rectangles (or shapes composed of rectangles) presented in problems by tiling and counting." },
  { code: "3.GSR.7.3", cluster: "3.GSR.7", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 43,
    text: "Discover and explain how area can be found by multiplying dimensions of a rectangle." },
  { code: "3.GSR.8.1", cluster: "3.GSR.8", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 43,
    text: "Determine the perimeter of a polygon and explain that the perimeter represents the distance around a polygon. Solve problems involving perimeters of polygons." },
  { code: "3.GSR.8.2", cluster: "3.GSR.8", grade: "3", gradeNum: 3, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 44,
    text: "Investigate and describe how rectangles with the same perimeter can have different areas or how rectangles with the same area can have different perimeters." },
  { code: "3.MDR.5.1", cluster: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 41,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to solve problems relevant to everyday life." },
  { code: "3.MDR.5.2", cluster: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 41,
    text: "Tell and write time to the nearest minute and estimate time to the nearest fifteen minutes (quarter hour) from the analysis of an analog clock." },
  { code: "3.MDR.5.3", cluster: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 41,
    text: "Solve meaningful problems involving elapsed time, including intervals of time to the hour, half hour, and quarter hour where the times presented are only on the hour, half hour, or quarter hour within a.m. or p.m. only." },
  { code: "3.MDR.5.4", cluster: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 41,
    text: "Use rulers to measure lengths in halves and fourths (quarters) of an inch and a whole inch." },
  { code: "3.MDR.5.5", cluster: "3.MDR.5", grade: "3", gradeNum: 3, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 41,
    text: "Estimate and measure liquid volumes, lengths and masses of objects using customary units. Solve problems involving mass, length, and volume given in the same unit, and reason about the relative sizes of measurement units within the customary system." },
  { code: "3.NR.1.1", cluster: "3.NR.1", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 36,
    text: "Read and write multi-digit whole numbers up to 10,000 using base-ten numerals and expanded form." },
  { code: "3.NR.1.2", cluster: "3.NR.1", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 36,
    text: "Use place value reasoning to compare multi-digit numbers up to 10,000, using >, =, and < symbols to record the results of comparisons." },
  { code: "3.NR.1.3", cluster: "3.NR.1", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 36,
    text: "Use place value understanding to round whole numbers up to 1000 to the nearest 10 or 100." },
  { code: "3.NR.4.1", cluster: "3.NR.4", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 40,
    text: "Describe a unit fraction and explain how multiple copies of a unit fraction form a non-unit fraction. Use parts of a whole, parts of a set, points on a number line, distances on a number line and area models." },
  { code: "3.NR.4.2", cluster: "3.NR.4", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 40,
    text: "Compare two unit fractions by flexibly using a variety of tools and strategies." },
  { code: "3.NR.4.3", cluster: "3.NR.4", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 40,
    text: "Represent fractions, including fractions greater than one, in multiple ways." },
  { code: "3.NR.4.4", cluster: "3.NR.4", grade: "3", gradeNum: 3, strand: "NR", strandName: "Numerical Reasoning", page: 40,
    text: "Recognize and generate simple equivalent fractions." },
  { code: "3.PAR.2.1", cluster: "3.PAR.2", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 37,
    text: "Fluently add and subtract within 1000 to solve problems." },
  { code: "3.PAR.2.2", cluster: "3.PAR.2", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 37,
    text: "Apply part-whole strategies, properties of operations and place value understanding, to solve problems involving addition and subtraction within 10,000. Represent these problems using equations with a letter standing for the unknown quantity. Justify solutions." },
  { code: "3.PAR.3.1", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 38,
    text: "Describe, extend, and create numeric patterns related to multiplication. Make predictions related to the patterns." },
  { code: "3.PAR.3.2", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 38,
    text: "Represent single digit multiplication and division facts using a variety of strategies. Explain the relationship between multiplication and division." },
  { code: "3.PAR.3.3", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 38,
    text: "Apply properties of operations (i.e., commutative property, associative property, distributive property) to multiply and divide within 100." },
  { code: "3.PAR.3.4", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 38,
    text: "Use the meaning of the equal sign to determine whether expressions involving addition, subtraction, and multiplication are equivalent." },
  { code: "3.PAR.3.5", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 39,
    text: "Use place value reasoning and properties of operations to multiply one-digit whole numbers by multiples of 10, in the range 10-90." },
  { code: "3.PAR.3.6", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 39,
    text: "Solve practical, relevant problems involving multiplication and division within 100 using part-whole strategies, visual representations, and/or concrete models." },
  { code: "3.PAR.3.7", cluster: "3.PAR.3", grade: "3", gradeNum: 3, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 39,
    text: "Use multiplication and division to solve problems involving whole numbers to 100. Represent these problems using equations with a letter standing for the unknown quantity. Justify solutions." },
  { code: "4.GSR.7.1", cluster: "4.GSR.7", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 58,
    text: "Recognize angles as geometric shapes formed when two rays share a common endpoint. Draw right, acute, and obtuse angles based on the relationship of the angle measure to 90 degrees." },
  { code: "4.GSR.7.2", cluster: "4.GSR.7", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 58,
    text: "Measure angles in reference to a circle with the center at the common endpoint of two rays. Determine an angle's measure in relation to the 360 degrees in a circle through division or as a missing factor problem." },
  { code: "4.GSR.8.1", cluster: "4.GSR.8", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 59,
    text: "Explore, investigate, and draw points, lines, line segments, rays, angles (right, acute, obtuse), perpendicular lines, parallel lines, and lines of symmetry. Identify these in two- dimensional figures." },
  { code: "4.GSR.8.2", cluster: "4.GSR.8", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 59,
    text: "Classify, compare, and contrast polygons based on lines of symmetry, the presence or absence of parallel or perpendicular line segments, or the presence or absence of angles of a specified size and based on side lengths." },
  { code: "4.GSR.8.3", cluster: "4.GSR.8", grade: "4", gradeNum: 4, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 60,
    text: "Solve problems involving area and perimeter of composite rectangles involving whole numbers with known side lengths." },
  { code: "4.MDR.6.1", cluster: "4.MDR.6", grade: "4", gradeNum: 4, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 57,
    text: "Use the four operations to solve problems involving elapsed time to the nearest minute, intervals of time, metric measurements of liquid volumes, lengths, distances, and masses of objects, including problems involving fractions with like denominators, and also problems that require expressing measurements given in a larger unit in terms of a smaller unit, and expressing a smaller unit in terms of a larger unit based on the idea of equivalence." },
  { code: "4.MDR.6.2", cluster: "4.MDR.6", grade: "4", gradeNum: 4, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 57,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to solve problems relevant to everyday life." },
  { code: "4.MDR.6.3", cluster: "4.MDR.6", grade: "4", gradeNum: 4, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 58,
    text: "Create dot plots to display a distribution of numerical (quantitative) measurement data." },
  { code: "4.NR.1.1", cluster: "4.NR.1", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 46,
    text: "Read and write multi-digit whole numbers to the hundred-thousands place using base-ten numerals and expanded form." },
  { code: "4.NR.1.2", cluster: "4.NR.1", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 46,
    text: "Recognize and show that a digit in one place has a value ten times greater than what it represents in the place to its right and extend this understanding to determine the value of a digit when it is shifted to the left or right, based on the relationship between multiplication and division." },
  { code: "4.NR.1.3", cluster: "4.NR.1", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 46,
    text: "Use place value reasoning to represent, compare, and order multi-digit numbers, using >, =, and < symbols to record the results of comparisons." },
  { code: "4.NR.1.4", cluster: "4.NR.1", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 46,
    text: "Use place value understanding to round multi-digit whole numbers." },
  { code: "4.NR.2.1", cluster: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 47,
    text: "Fluently add and subtract multi-digit numbers to solve practical, mathematical problems using place value understanding, properties of operations, and relationships between operations." },
  { code: "4.NR.2.2", cluster: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 47,
    text: "Interpret, model, and solve problems involving multiplicative comparison." },
  { code: "4.NR.2.3", cluster: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 47,
    text: "Solve relevant problems involving multiplication of a number with up to four digits by a 1-digit whole number or involving multiplication of two two-digit numbers using strategies based on place value and the properties of operations. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models." },
  { code: "4.NR.2.4", cluster: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 48,
    text: "Solve authentic division problems involving up to 4-digit dividends and 1- digit divisors (including whole number quotients with remainders) using strategies based on place-value understanding, properties of operations, and the relationships between operations." },
  { code: "4.NR.2.5", cluster: "4.NR.2", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 48,
    text: "Solve multi-step problems using addition, subtraction, multiplication, and division involving whole numbers. Use mental computation and estimation strategies to justify the reasonableness of solutions." },
  { code: "4.NR.4.1", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 51,
    text: "Using concrete materials, drawings, and number lines, demonstrate and explain the relationship between equivalent fractions, including fractions greater than one, and explain the identity property of multiplication as it relates to equivalent fractions. Generate equivalent fractions using these relationships." },
  { code: "4.NR.4.2", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 51,
    text: "Compare two fractions with the same numerator or the same denominator by reasoning about their size and recognize that comparisons are valid only when the two fractions refer to the same whole." },
  { code: "4.NR.4.3", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 52,
    text: "Compare two fractions with different numerators and/or different denominators by flexibly using a variety of tools and strategies and recognize that comparisons are valid only when the two fractions refer to the same whole." },
  { code: "4.NR.4.4", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 53,
    text: "Represent whole numbers and fractions as the sum of unit fractions." },
  { code: "4.NR.4.5", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 53,
    text: "Represent a fraction as a sum of fractions with the same denominator in more than one way, recording with an equation." },
  { code: "4.NR.4.6", cluster: "4.NR.4", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 54,
    text: "Add and subtract fractions and mixed numbers with like denominators using a variety of tools." },
  { code: "4.NR.5.1", cluster: "4.NR.5", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 55,
    text: "Demonstrate and explain the concept of equivalent fractions with denominators of 10 and 100, using concrete materials and visual models. Add two fractions with denominators of 10 and 100." },
  { code: "4.NR.5.2", cluster: "4.NR.5", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 56,
    text: "Represent, read, and write fractions with denominators of 10 or 100 using decimal notation, and decimal numbers to the hundredths place as fractions, using concrete materials and drawings." },
  { code: "4.NR.5.3", cluster: "4.NR.5", grade: "4", gradeNum: 4, strand: "NR", strandName: "Numerical Reasoning", page: 56,
    text: "Compare two decimal numbers to the hundredths place by reasoning about their size. Record the results of comparisons with the symbols >, =, or <, and justify the conclusions." },
  { code: "4.PAR.3.1", cluster: "4.PAR.3", grade: "4", gradeNum: 4, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 49,
    text: "Generate both number and shape patterns that follow a provided rule." },
  { code: "4.PAR.3.2", cluster: "4.PAR.3", grade: "4", gradeNum: 4, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 50,
    text: "Use input-output rules, tables, and charts to represent and describe patterns, find relationships, and solve problems." },
  { code: "4.PAR.3.3", cluster: "4.PAR.3", grade: "4", gradeNum: 4, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 50,
    text: "Find factor pairs in the range 1–100 and find multiples of single-digit numbers up to 100." },
  { code: "4.PAR.3.4", cluster: "4.PAR.3", grade: "4", gradeNum: 4, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 50,
    text: "Identify composite numbers and prime numbers and explain the relationship with the factor pairs." },
  { code: "5.GSR.8.1", cluster: "5.GSR.8", grade: "5", gradeNum: 5, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 70,
    text: "Classify, compare, and contrast polygons based on properties." },
  { code: "5.GSR.8.2", cluster: "5.GSR.8", grade: "5", gradeNum: 5, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 70,
    text: "Determine, through exploration and investigation, that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category." },
  { code: "5.GSR.8.3", cluster: "5.GSR.8", grade: "5", gradeNum: 5, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 70,
    text: "Investigate volume of right rectangular prisms by packing them with unit cubes without gaps or overlaps. Then, determine the total volume to solve problems." },
  { code: "5.GSR.8.4", cluster: "5.GSR.8", grade: "5", gradeNum: 5, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 70,
    text: "Discover and explain how the volume of a right rectangular prism can be found by multiplying the area of the base times the height to solve authentic, mathematical problems." },
  { code: "5.MDR.7.1", cluster: "5.MDR.7", grade: "5", gradeNum: 5, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 69,
    text: "Explore realistic problems involving different units of measurement, including distance, mass, weight, volume, and time." },
  { code: "5.MDR.7.2", cluster: "5.MDR.7", grade: "5", gradeNum: 5, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 69,
    text: "Ask questions and answer them based on gathered information, observations, and appropriate graphical displays to solve problems relevant to everyday life." },
  { code: "5.MDR.7.3", cluster: "5.MDR.7", grade: "5", gradeNum: 5, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 69,
    text: "Convert among units within the metric system and then apply these conversions to solve multi-step, practical problems." },
  { code: "5.MDR.7.4", cluster: "5.MDR.7", grade: "5", gradeNum: 5, strand: "MDR", strandName: "Measurement & Data Reasoning", page: 69,
    text: "Convert among units within relative sizes of measurement units within the customary measurement system." },
  { code: "5.NR.1.1", cluster: "5.NR.1", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 62,
    text: "Explain that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left." },
  { code: "5.NR.1.2", cluster: "5.NR.1", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 62,
    text: "Explain patterns in the placement of digits when multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10, up to 103." },
  { code: "5.NR.2.1", cluster: "5.NR.2", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 62,
    text: "Fluently multiply multi-digit (up to 3- digit by 2-digit) whole numbers to solve authentic problems." },
  { code: "5.NR.2.2", cluster: "5.NR.2", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 63,
    text: "Fluently divide multi-digit whole numbers (up to 4-digit dividends and 2-digit divisors no greater than 25) to solve practical problems." },
  { code: "5.NR.3.1", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 63,
    text: "Explain the meaning of a fraction as division of the numerator by the denominator ( 𝑎 = a ÷ b). Solve 𝑏 problems involving division of whole numbers leading to answers in the form of fractions or mixed numbers." },
  { code: "5.NR.3.2", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 63,
    text: "Compare and order up to three fractions with different numerators and/or different denominators by flexibly using a variety of tools and strategies." },
  { code: "5.NR.3.3", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 64,
    text: "Model and solve problems involving addition and subtraction of fractions and mixed numbers with unlike denominators." },
  { code: "5.NR.3.4", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 64,
    text: "Model and solve problems involving multiplication of a fraction and a whole number." },
  { code: "5.NR.3.5", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 65,
    text: "Explain why multiplying a whole number by a fraction greater than one results in a product greater than the whole number, and why multiplying a whole number by a fraction less than one results in a product less than the whole number and multiplying a whole number by a fraction equal to one results in a product equal to the whole number." },
  { code: "5.NR.3.6", cluster: "5.NR.3", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 65,
    text: "Model and solve problems involving division of a unit fraction by a whole number and a whole number by a unit fraction." },
  { code: "5.NR.4.1", cluster: "5.NR.4", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 66,
    text: "Read and write decimal numbers to the thousandths place using base- ten numerals written in standard form and expanded form." },
  { code: "5.NR.4.2", cluster: "5.NR.4", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 66,
    text: "Represent, compare, and order decimal numbers to the thousandths place based on the meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons." },
  { code: "5.NR.4.3", cluster: "5.NR.4", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 66,
    text: "Use place value understanding to round decimal numbers to the hundredths place." },
  { code: "5.NR.4.4", cluster: "5.NR.4", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 66,
    text: "Solve problems involving addition and subtraction of decimal numbers to the hundredths place using a variety of strategies." },
  { code: "5.NR.5.1", cluster: "5.NR.5", grade: "5", gradeNum: 5, strand: "NR", strandName: "Numerical Reasoning", page: 67,
    text: "Write, interpret, and evaluate simple numerical expressions involving whole numbers with or without grouping symbols to represent actual situations." },
  { code: "5.PAR.6.1", cluster: "5.PAR.6", grade: "5", gradeNum: 5, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 68,
    text: "Generate two numerical patterns using two given rules. Identify apparent relationships between corresponding terms by completing a table." },
  { code: "5.PAR.6.2", cluster: "5.PAR.6", grade: "5", gradeNum: 5, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 68,
    text: "Represent problems by plotting ordered pairs and explain coordinate values of points in the first quadrant of the coordinate plane." },
  { code: "6.GSR.5.1", cluster: "6.GSR.5", grade: "6", gradeNum: 6, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 85,
    text: "Explore area as a measurable attribute of triangles, quadrilaterals, and other polygons conceptually by composing or decomposing into rectangles, triangles, and other shapes. Find the area of these geometric figures to solve problems." },
  { code: "6.GSR.5.2", cluster: "6.GSR.5", grade: "6", gradeNum: 6, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 86,
    text: "Given the net of three-dimensional figures with rectangular and triangular faces, determine the surface area of these figures." },
  { code: "6.GSR.5.3", cluster: "6.GSR.5", grade: "6", gradeNum: 6, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 86,
    text: "Calculate the volume of right rectangular prisms with fractional edge lengths by applying the formula, V = (area of base) x (height)." },
  { code: "6.NR.1.1", cluster: "6.NR.1", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 77,
    text: "Fluently add and subtract any combination of fractions to solve problems." },
  { code: "6.NR.1.2", cluster: "6.NR.1", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 77,
    text: "Multiply and divide any combination of whole numbers, fractions, and mixed numbers using a student-selected strategy. Interpret products and quotients of fractions and solve word problems." },
  { code: "6.NR.1.3", cluster: "6.NR.1", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 78,
    text: "Perform operations with multi-digit decimal numbers fluently using models and student-selected strategies." },
  { code: "6.NR.2.1", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 78,
    text: "Describe and interpret the center of the distribution by the equal share value (mean)." },
  { code: "6.NR.2.2", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 78,
    text: "Summarize categorical and quantitative (numerical) data sets in relation to the context: display the distributions of quantitative (numerical) data in plots on a number line, including dot plots, histograms, and box plots and display the distribution of categorical data using bar graphs." },
  { code: "6.NR.2.3", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 79,
    text: "Interpret numerical data to answer a statistical investigative question created. Describe the distribution of a quantitative (numerical) variable collected, including its center, variability, and overall shape." },
  { code: "6.NR.2.4", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 80,
    text: "Design simple experiments and collect data. Use data gathered from realistic scenarios and simulations to determine quantitative measures of center (median and/or mean) and variability (interquartile range and range). Use these quantities to draw conclusions about the data, compare different numerical data sets, and make predictions." },
  { code: "6.NR.2.5", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 80,
    text: "Relate the choice of measures of center and variability to the shape of the data distribution and the context in which the data were gathered." },
  { code: "6.NR.2.6", cluster: "6.NR.2", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 80,
    text: "Describe the impact that inserting or deleting a data point has on the mean and the median of a data set. Create data displays using a dot plot or box plot to examine this impact." },
  { code: "6.NR.3.1", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 81,
    text: "Identify and compare integers and explain the meaning of zero based on multiple authentic situations." },
  { code: "6.NR.3.2", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 81,
    text: "Order and plot integers on a number line and use distance from zero to discover the connection between integers and their opposites." },
  { code: "6.NR.3.3", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 81,
    text: "Recognize and explain that opposite signs of integers indicate locations on opposite sides of zero on the number line; recognize and explain that the opposite of the opposite of a number is the number itself." },
  { code: "6.NR.3.4", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 81,
    text: "Write, interpret, and explain statements of order for rational numbers in authentic, mathematical situations. Compare rational numbers, including integers, using equality and inequality symbols." },
  { code: "6.NR.3.5", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 82,
    text: "Explain the absolute value of a rational number as its distance from zero on the number line; interpret absolute value as distance for a positive or negative quantity in a relevant situation." },
  { code: "6.NR.3.6", cluster: "6.NR.3", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 82,
    text: "Distinguish comparisons of absolute value from statements about order." },
  { code: "6.NR.4.1", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 83,
    text: "Explain the concept of a ratio, represent ratios, and use ratio language to describe a relationship between two quantities." },
  { code: "6.NR.4.2", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 83,
    text: "Make tables of equivalent ratios relating quantities with whole-number measurements, find missing values in the tables, and plot the pairs of values on the coordinate plane. Use tables to compare ratios." },
  { code: "6.NR.4.3", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 83,
    text: "Solve problems involving proportions using a variety of student-selected strategies." },
  { code: "6.NR.4.4", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 83,
    text: "Describe the concept of rates and unit rate in the context of a ratio relationship." },
  { code: "6.NR.4.5", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 84,
    text: "Solve unit rate problems including those involving unit pricing and constant speed." },
  { code: "6.NR.4.6", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 84,
    text: "Calculate a percent of a quantity as a rate per 100 and solve everyday problems given a percent." },
  { code: "6.NR.4.7", cluster: "6.NR.4", grade: "6", gradeNum: 6, strand: "NR", strandName: "Numerical Reasoning", page: 84,
    text: "Use ratios to convert within measurement systems (customary and metric) to solve authentic problems that exist in everyday life." },
  { code: "6.PAR.6.1", cluster: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 86,
    text: "Write and evaluate numerical expressions involving rational bases and whole-number exponents." },
  { code: "6.PAR.6.2", cluster: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 86,
    text: "Determine greatest common factors and least common multiples using a variety of strategies to make sense of applicable problems." },
  { code: "6.PAR.6.3", cluster: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 87,
    text: "Write and read expressions that represent operations with numbers and variables in realistic situations." },
  { code: "6.PAR.6.4", cluster: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 87,
    text: "Evaluate expressions when given values for the variables, including expressions that arise in everyday situations." },
  { code: "6.PAR.6.5", cluster: "6.PAR.6", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 87,
    text: "Apply the properties of operations to identify and generate equivalent expressions." },
  { code: "6.PAR.7.1", cluster: "6.PAR.7", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 88,
    text: "Solve one-step equations and inequalities involving variables when values for the variables are given. Determine whether an equation and inequality involving a variable is true or false for a given value of the variable." },
  { code: "6.PAR.7.2", cluster: "6.PAR.7", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 88,
    text: "Write one-step equations and inequalities to represent and solve problems; explain that a variable can represent an unknown number or any number in a specified set." },
  { code: "6.PAR.7.3", cluster: "6.PAR.7", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 88,
    text: "Solve problems by writing and solving equations of the form x + p = q, px = q and 𝑥 = 𝑝 q for cases in which p, q and x are all nonnegative rational numbers." },
  { code: "6.PAR.7.4", cluster: "6.PAR.7", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 88,
    text: "Recognize and generate inequalities of the form x > c, x > c, x < c, or x < c to explain situations that have infinitely many solutions; represent solutions of such inequalities on a number line." },
  { code: "6.PAR.8.1", cluster: "6.PAR.8", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 89,
    text: "Locate and position rational numbers on a horizontal or vertical number line; find and position pairs of integers and other rational numbers on a coordinate plane." },
  { code: "6.PAR.8.2", cluster: "6.PAR.8", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 89,
    text: "Show and explain that signs of numbers in ordered pairs indicate locations in quadrants of the coordinate plane and determine how two ordered pairs may differ based only on the signs." },
  { code: "6.PAR.8.3", cluster: "6.PAR.8", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 89,
    text: "Solve problems by graphing points in all four quadrants of the coordinate plane. Include use of coordinates and absolute value to find distances between points with the same x- coordinate or the same y-coordinate." },
  { code: "6.PAR.8.4", cluster: "6.PAR.8", grade: "6", gradeNum: 6, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 89,
    text: "Draw polygons in the coordinate plane given coordinates for the vertices; use coordinates to find the length of a side joining points with the same x-coordinate or the same y- coordinate." },
  { code: "7.GSR.5.1", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 97,
    text: "Measure angles in whole non- standard units." },
  { code: "7.GSR.5.2", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 97,
    text: "Measure angles in whole number degrees using a protractor." },
  { code: "7.GSR.5.3", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 98,
    text: "Use facts about supplementary, complementary, vertical, and adjacent angles in a multi-step problem to write and solve equations for an unknown angle in a figure." },
  { code: "7.GSR.5.4", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 98,
    text: "Explore and describe the relationship between pi, radius, diameter, circumference, and area of a circle to derive the formulas for the circumference and area of a circle." },
  { code: "7.GSR.5.5", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 98,
    text: "Given the formula for the area and circumference of a circle, solve problems that exist in everyday life." },
  { code: "7.GSR.5.6", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 99,
    text: "Solve realistic problems involving surface area of right prisms and cylinders." },
  { code: "7.GSR.5.7", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 99,
    text: "Describe the two-dimensional figures (cross sections) that result from slicing three-dimensional figures, as in the plane sections of right rectangular prisms, right rectangular pyramids, cones, cylinders, and spheres." },
  { code: "7.GSR.5.8", cluster: "7.GSR.5", grade: "7", gradeNum: 7, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 99,
    text: "Explore volume as a measurable attribute of cylinders and right prisms. Find the volume of these geometric figures using concrete problems." },
  { code: "7.NR.1.1", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 91,
    text: "Show that a number and its opposite have a sum of 0 (are additive inverses). Describe situations in which opposite quantities combine to make 0." },
  { code: "7.NR.1.2", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 91,
    text: "Show and explain p + q as the number located a distance |q| from p, in the positive or negative direction, depending on whether q is positive or negative. Interpret sums of rational numbers by describing applicable situations." },
  { code: "7.NR.1.3", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 91,
    text: "Represent addition and subtraction with rational numbers on a horizontal or a vertical number line diagram to solve authentic problems." },
  { code: "7.NR.1.4", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 91,
    text: "Show and explain subtraction of rational numbers as adding the additive inverse, p – q = p + (–q). Show that the distance between two rational numbers on the number line is the absolute value of their difference and apply this principle in contextual situations." },
  { code: "7.NR.1.5", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 91,
    text: "Apply properties of operations, including part-whole reasoning, as strategies to add and subtract rational numbers." },
  { code: "7.NR.1.6", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 92,
    text: "Make sense of multiplication of rational numbers using realistic applications." },
  { code: "7.NR.1.7", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 92,
    text: "Show and explain that integers can be divided, assuming the divisor is not zero, and every quotient of integers is a rational number." },
  { code: "7.NR.1.8", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 92,
    text: "Represent the multiplication and division of integers using a variety of strategies and interpret products and quotients of rational numbers by describing them based on the relevant situation." },
  { code: "7.NR.1.9", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 92,
    text: "Apply properties of operations as strategies to solve multiplication and division problems involving rational numbers represented in an applicable scenario." },
  { code: "7.NR.1.10", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 92,
    text: "Convert rational numbers between forms to include fractions, decimal numbers and percentages, using understanding of the part divided by the whole. Know that the decimal form of a rational number terminates in 0s or eventually repeats." },
  { code: "7.NR.1.11", cluster: "7.NR.1", grade: "7", gradeNum: 7, strand: "NR", strandName: "Numerical Reasoning", page: 93,
    text: "Solve multi-step, contextual problems involving rational numbers, converting between forms as appropriate, and assessing the reasonableness of answers using mental computation and estimation strategies." },
  { code: "7.PAR.2.1", cluster: "7.PAR.2", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 93,
    text: "Apply properties of operations as strategies to add, subtract, factor, and expand linear expressions with rational coefficients." },
  { code: "7.PAR.2.2", cluster: "7.PAR.2", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 93,
    text: "Rewrite an expression in different forms from a contextual problem to clarify the problem and show how the quantities in it are related." },
  { code: "7.PAR.3.1", cluster: "7.PAR.3", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 93,
    text: "Construct algebraic equations to solve practical problems leading to equations of the form px + q = r and p(x + q) = r, where p, q, and r are specific rational numbers. Interpret the solution based on the situation." },
  { code: "7.PAR.3.2", cluster: "7.PAR.3", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 94,
    text: "Construct algebraic inequalities to solve problems, leading to inequalities of the form px + q > r, px + q < r, px + q ≤ r, or px + q ≥ r, where p, q, and r are specific rational numbers. Graph and interpret the solution based on the realistic situation that the inequalities represent." },
  { code: "7.PAR.4.1", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 94,
    text: "Compute unit rates associated with ratios of fractions, including ratios of lengths, areas and other quantities measured in like or different units presented in realistic problems." },
  { code: "7.PAR.4.2", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 95,
    text: "Determine the unit rate (constant of proportionality) in tables, graphs (1, r), equations, diagrams, and verbal descriptions of proportional relationships to solve realistic problems." },
  { code: "7.PAR.4.3", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 95,
    text: "Determine whether two quantities presented in authentic problems are in a proportional relationship." },
  { code: "7.PAR.4.4", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 95,
    text: "Identify, represent, and use proportional relationships." },
  { code: "7.PAR.4.5", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 95,
    text: "Use context to explain what a point (x, y) on the graph of a proportional relationship means in terms of the situation, with special attention to the points (0, 0) and (1, r) where r is the unit rate." },
  { code: "7.PAR.4.6", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 95,
    text: "Solve everyday problems involving scale drawings of geometric figures, including computing actual lengths and areas from a scale drawing and reproducing a scale drawing at a different scale." },
  { code: "7.PAR.4.7", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 96,
    text: "Use similar triangles to explain why the slope, m, is the same between any two distinct points on a non- vertical line in the coordinate plane." },
  { code: "7.PAR.4.8", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 96,
    text: "Graph proportional relationships, interpreting the unit rate as the slope of the graph. Compare two different proportional relationships represented in different ways." },
  { code: "7.PAR.4.9", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 96,
    text: "Use proportional relationships to solve multi-step ratio and percent problems presented in applicable situations." },
  { code: "7.PAR.4.10", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 96,
    text: "Predict characteristics of a population by examining the characteristics of a representative sample. Recognize the potential limitations and scope of the sample to the population." },
  { code: "7.PAR.4.11", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 97,
    text: "Analyze sampling methods and conclude that random sampling produces and supports valid inferences." },
  { code: "7.PAR.4.12", cluster: "7.PAR.4", grade: "7", gradeNum: 7, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 97,
    text: "Use data from repeated random samples to evaluate how much a sample mean is expected to vary from a population mean. Simulate multiple samples of the same size." },
  { code: "7.PR.6.1", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Represent the probability of a chance event as a number between 0 and 1 that expresses the likelihood of the event occurring. Describe that a probability near 0 indicates an unlikely event, a probability around 1/2 indicates an event that is neither unlikely nor likely, and a probability near 1 indicates a likely event." },
  { code: "7.PR.6.2", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Approximate the probability of a chance event by collecting data on an event and observing its long-run relative frequency will approach the theoretical probability." },
  { code: "7.PR.6.3", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Develop a probability model and use it to find probabilities of simple events. Compare experimental and theoretical probabilities of events. If the probabilities are not close, explain possible sources of the discrepancy." },
  { code: "7.PR.6.4", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Develop a uniform probability model by assigning equal probability to all outcomes and use the model to determine probabilities of events." },
  { code: "7.PR.6.5", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Develop a probability model (which may not be uniform) by observing frequencies in data generated from a chance process." },
  { code: "7.PR.6.6", cluster: "7.PR.6", grade: "7", gradeNum: 7, strand: "PR", strandName: "Probability Reasoning", page: 101,
    text: "Use appropriate graphical displays and numerical summaries from data distributions with categorical or quantitative (numerical) variables as probability models to draw informal inferences about two samples or populations." },
  { code: "8.FGR.5.1", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 108,
    text: "Show and explain that a function is a rule that assigns to each input exactly one output." },
  { code: "8.FGR.5.2", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 108,
    text: "Within realistic situations, identify and describe examples of functions that are linear or nonlinear. Sketch a graph that exhibits the qualitative features of a function that has been described verbally." },
  { code: "8.FGR.5.3", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 108,
    text: "Relate the domain of a linear function to its graph and where applicable to the quantitative relationship it describes." },
  { code: "8.FGR.5.4", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 108,
    text: "Compare properties (rate of change and initial value) of two functions used to model an authentic situation each represented in a different way (algebraically, graphically, numerically in tables, or by verbal descriptions)." },
  { code: "8.FGR.5.5", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 108,
    text: "Write and explain the equations y = mx + b (slope-intercept form), Ax + By = C (standard form), and (y - y1) = m(x - x1) (point-slope form) as defining a linear function whose graph is a straight line to reveal and explain different properties of the function." },
  { code: "8.FGR.5.6", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 109,
    text: "Write a linear function defined by an expression in different but equivalent forms to reveal and explain different properties of the function." },
  { code: "8.FGR.5.7", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 109,
    text: "Construct a function to model a linear relationship between two quantities. Determine the rate of change and initial value of the function from a description of a relationship or from two (x,y) values, including reading these from a table or from a graph." },
  { code: "8.FGR.5.8", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 109,
    text: "Explain the meaning of the rate of change and initial value of a linear function in terms of the situation it models, and in terms of its graph or a table of values." },
  { code: "8.FGR.5.9", cluster: "8.FGR.5", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 109,
    text: "Graph and analyze linear functions expressed in various algebraic forms and show key characteristics of the graph to describe applicable situations." },
  { code: "8.FGR.6.1", cluster: "8.FGR.6", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 109,
    text: "Show that straight lines are widely used to model relationships between two quantitative variables. For scatter plots that suggest a linear association, visually fit a straight line, and informally assess the model fit by judging the closeness of the data points to the line of best fit." },
  { code: "8.FGR.6.2", cluster: "8.FGR.6", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 110,
    text: "Use the equation of a linear model to solve problems in the context of bivariate measurement data, interpreting the slope and intercepts." },
  { code: "8.FGR.6.3", cluster: "8.FGR.6", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 110,
    text: "Explain the meaning of the predicted slope (rate of change) and the predicted intercept (constant term) of a linear model in the context of the data." },
  { code: "8.FGR.6.4", cluster: "8.FGR.6", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 110,
    text: "Use appropriate graphical displays from data distributions involving lines of best fit to draw informal inferences and answer the statistical investigative question posed in an unbiased statistical study." },
  { code: "8.FGR.7.1", cluster: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 110,
    text: "Interpret and solve relevant mathematical problems leading to two linear equations in two variables." },
  { code: "8.FGR.7.2", cluster: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 110,
    text: "Show and explain that solutions to a system of two linear equations in two variables correspond to points of intersection of their graphs, because the points of intersection satisfy both equations simultaneously." },
  { code: "8.FGR.7.3", cluster: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 111,
    text: "Approximate solutions of two linear equations in two variables by graphing the equations and solving simple cases by inspection." },
  { code: "8.FGR.7.4", cluster: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 111,
    text: "Analyze and solve systems of two linear equations in two variables algebraically to find exact solutions." },
  { code: "8.FGR.7.5", cluster: "8.FGR.7", grade: "8", gradeNum: 8, strand: "FGR", strandName: "Functional & Graphical Reasoning", page: 111,
    text: "Create and compare the equations of two lines that are either parallel to each other, perpendicular to each other, or neither parallel nor perpendicular." },
  { code: "8.GSR.8.1", cluster: "8.GSR.8", grade: "8", gradeNum: 8, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 112,
    text: "Explain a proof of the Pythagorean Theorem and its converse using visual models." },
  { code: "8.GSR.8.2", cluster: "8.GSR.8", grade: "8", gradeNum: 8, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 112,
    text: "Apply the Pythagorean Theorem to determine unknown side lengths in right triangles within authentic, mathematical problems in two and three dimensions." },
  { code: "8.GSR.8.3", cluster: "8.GSR.8", grade: "8", gradeNum: 8, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 112,
    text: "Apply the Pythagorean Theorem to find the distance between two points in a coordinate system in practical, mathematical problems." },
  { code: "8.GSR.8.4", cluster: "8.GSR.8", grade: "8", gradeNum: 8, strand: "GSR", strandName: "Geometric & Spatial Reasoning", page: 113,
    text: "Apply the formulas for the volume of cones, cylinders, and spheres and use them to solve in relevant problems." },
  { code: "8.NR.1.1", cluster: "8.NR.1", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 104,
    text: "Distinguish between rational and irrational numbers using decimal expansion. Convert a decimal expansion which repeats eventually into a rational number." },
  { code: "8.NR.1.2", cluster: "8.NR.1", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 104,
    text: "Approximate irrational numbers to compare the size of irrational numbers, locate them approximately on a number line, and estimate the value of expressions." },
  { code: "8.NR.2.1", cluster: "8.NR.2", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 105,
    text: "Apply the properties of integer exponents to generate equivalent numerical expressions." },
  { code: "8.NR.2.2", cluster: "8.NR.2", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 105,
    text: "Use square root and cube root symbols to represent solutions to equations. Recognize that x2 = p (where p is a positive rational number and |x| ≤ 25) has two solutions and x3 = p (where p is a negative or positive rational number and |x| ≤ 10) has one solution. Evaluate square roots of perfect squares ≤ 625 and cube roots of perfect cubes ≥ -1000 and ≤ 1000." },
  { code: "8.NR.2.3", cluster: "8.NR.2", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 105,
    text: "Use numbers expressed in scientific notation to estimate very large or very small quantities, and to express how many times as much one is than the other." },
  { code: "8.NR.2.4", cluster: "8.NR.2", grade: "8", gradeNum: 8, strand: "NR", strandName: "Numerical Reasoning", page: 105,
    text: "Add, subtract, multiply and divide numbers expressed in scientific notation, including problems where both decimal and scientific notation are used. Interpret scientific notation that has been generated by technology (e.g., calculators or online technology tools)." },
  { code: "8.PAR.3.1", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Interpret expressions and parts of an expression, in context, by utilizing formulas or expressions with multiple terms and/or factors." },
  { code: "8.PAR.3.2", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Describe and solve linear equations in one variable with one solution (x = a), infinitely many solutions (a = a), or no solutions (a = b). Show which of these possibilities is the case by successively transforming the given equation into simpler forms, until an equivalent equation of the form x = a, a = a, or a = b results (where a and b are different numbers)." },
  { code: "8.PAR.3.3", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Create and solve linear equations and inequalities in one variable within a relevant application." },
  { code: "8.PAR.3.4", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Using algebraic properties and the properties of real numbers, justify the steps of a one-solution equation or inequality." },
  { code: "8.PAR.3.5", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Solve linear equations and inequalities in one variable with coefficients represented by letters and explain the solution based on the contextual, mathematical situation." },
  { code: "8.PAR.3.6", cluster: "8.PAR.3", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 106,
    text: "Use algebraic reasoning to fluently manipulate linear and literal equations expressed in various forms to solve relevant, mathematical problems." },
  { code: "8.PAR.4.1", cluster: "8.PAR.4", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 107,
    text: "Use the equation y = mx (proportional) for a line through the origin to derive the equation y = mx + b (non-proportional) for a line intersecting the vertical axis at b." },
  { code: "8.PAR.4.2", cluster: "8.PAR.4", grade: "8", gradeNum: 8, strand: "PAR", strandName: "Patterning & Algebraic Reasoning", page: 107,
    text: "Show and explain that the graph of an equation representing an applicable situation in two variables is the set of all its solutions plotted in the coordinate plane." },
];
